--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create lefttop_dark_bg
local lefttop_dark_bg = ccui.ImageView:create()
lefttop_dark_bg:ignoreContentAdaptWithSize(false)
lefttop_dark_bg:loadTexture("app/part/xymj/newwifiandnet/res/scale9dark_bg.png",0)
lefttop_dark_bg:setScale9Enabled(true)
lefttop_dark_bg:setCapInsets({x = 4, y = -3, width = 22, height = 36})
lefttop_dark_bg:setLayoutComponentEnabled(true)
lefttop_dark_bg:setName("lefttop_dark_bg")
lefttop_dark_bg:setTag(668)
lefttop_dark_bg:setCascadeColorEnabled(true)
lefttop_dark_bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(lefttop_dark_bg)
layout:setSize({width = 212.0000, height = 38.0000})
layout:setLeftMargin(-106.0000)
layout:setRightMargin(-106.0000)
layout:setTopMargin(-19.0000)
layout:setBottomMargin(-19.0000)
Node:addChild(lefttop_dark_bg)

--Create wifi_img
local wifi_img = ccui.ImageView:create()
wifi_img:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/newwifiandnet/res/wbn_picture.plist")
wifi_img:loadTexture("app/part/xymj/newwifiandnet/res/wifi-0.png",1)
wifi_img:setLayoutComponentEnabled(true)
wifi_img:setName("wifi_img")
wifi_img:setTag(79)
wifi_img:setCascadeColorEnabled(true)
wifi_img:setCascadeOpacityEnabled(true)
wifi_img:setPosition(20.0652, 19.0398)
layout = ccui.LayoutComponent:bindLayoutComponent(wifi_img)
layout:setPositionPercentX(0.0946)
layout:setPositionPercentY(0.5010)
layout:setPercentWidth(0.1651)
layout:setPercentHeight(0.7105)
layout:setSize({width = 35.0000, height = 27.0000})
layout:setLeftMargin(2.5652)
layout:setRightMargin(174.4348)
layout:setTopMargin(5.4602)
layout:setBottomMargin(5.5398)
lefttop_dark_bg:addChild(wifi_img)

--Create time_txt
local time_txt = ccui.TextAtlas:create([[11/12]],
													"app/part/xymj/newwifiandnet/res/atlas_digits_time.png",
													15,
													24,
													"/")
time_txt:setLayoutComponentEnabled(true)
time_txt:setName("time_txt")
time_txt:setTag(649)
time_txt:setCascadeColorEnabled(true)
time_txt:setCascadeOpacityEnabled(true)
time_txt:setPosition(75.0407, 20.0397)
time_txt:setScaleX(0.8000)
time_txt:setScaleY(0.9800)
layout = ccui.LayoutComponent:bindLayoutComponent(time_txt)
layout:setPositionPercentX(0.3540)
layout:setPositionPercentY(0.5274)
layout:setPercentWidth(0.3538)
layout:setPercentHeight(0.6316)
layout:setSize({width = 75.0000, height = 24.0000})
layout:setLeftMargin(37.5407)
layout:setRightMargin(99.4593)
layout:setTopMargin(5.9603)
layout:setBottomMargin(8.0397)
lefttop_dark_bg:addChild(time_txt)

--Create battery
local battery = cc.Sprite:create("app/part/xymj/newwifiandnet/res/battery_bg.png")
battery:setName("battery")
battery:setTag(655)
battery:setCascadeColorEnabled(true)
battery:setCascadeOpacityEnabled(true)
battery:setPosition(126.6209, 20.1100)
layout = ccui.LayoutComponent:bindLayoutComponent(battery)
layout:setPositionPercentX(0.5973)
layout:setPositionPercentY(0.5292)
layout:setPercentWidth(0.1651)
layout:setPercentHeight(0.5000)
layout:setSize({width = 35.0000, height = 19.0000})
layout:setLeftMargin(109.1209)
layout:setRightMargin(67.8791)
layout:setTopMargin(8.3900)
layout:setBottomMargin(10.6100)
battery:setBlendFunc({src = 1, dst = 771})
lefttop_dark_bg:addChild(battery)

--Create battery_clip
local battery_clip = ccui.Layout:create()
battery_clip:ignoreContentAdaptWithSize(false)
battery_clip:setClippingEnabled(true)
battery_clip:setBackGroundColorType(1)
battery_clip:setBackGroundColor({r = 150, g = 200, b = 255})
battery_clip:setBackGroundColorOpacity(102)
battery_clip:setTouchEnabled(true);
battery_clip:setLayoutComponentEnabled(true)
battery_clip:setName("battery_clip")
battery_clip:setTag(656)
battery_clip:setCascadeColorEnabled(true)
battery_clip:setCascadeOpacityEnabled(true)
battery_clip:setAnchorPoint(0.5000, 0.5000)
battery_clip:setPosition(15.9580, 9.4576)
layout = ccui.LayoutComponent:bindLayoutComponent(battery_clip)
layout:setPositionPercentX(0.4559)
layout:setPositionPercentY(0.4978)
layout:setPercentWidth(0.6857)
layout:setPercentHeight(0.5789)
layout:setSize({width = 24.0000, height = 11.0000})
layout:setLeftMargin(3.9580)
layout:setRightMargin(7.0420)
layout:setTopMargin(4.0424)
layout:setBottomMargin(3.9576)
battery:addChild(battery_clip)

--Create battery_fore
local battery_fore = cc.Sprite:create("app/part/xymj/newwifiandnet/res/battery_fg.png")
battery_fore:setName("battery_fore")
battery_fore:setTag(657)
battery_fore:setCascadeColorEnabled(true)
battery_fore:setCascadeOpacityEnabled(true)
battery_fore:setAnchorPoint(0.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(battery_fore)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 24.0000, height = 11.0000})
battery_fore:setBlendFunc({src = 1, dst = 771})
battery_clip:addChild(battery_fore)

--Create R_bamboo_1_1
local R_bamboo_1_1 = cc.Sprite:create("Default/Sprite.png")
R_bamboo_1_1:setName("R_bamboo_1_1")
R_bamboo_1_1:setTag(8)
R_bamboo_1_1:setCascadeColorEnabled(true)
R_bamboo_1_1:setCascadeOpacityEnabled(true)
R_bamboo_1_1:setVisible(false)
R_bamboo_1_1:setPosition(-333.0000, -35.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(R_bamboo_1_1)
layout:setSize({width = 46.0000, height = 46.0000})
layout:setLeftMargin(-356.0000)
layout:setRightMargin(310.0000)
layout:setTopMargin(12.0000)
layout:setBottomMargin(-58.0000)
R_bamboo_1_1:setBlendFunc({src = 1, dst = 771})
Node:addChild(R_bamboo_1_1)

--Create R_bamboo_2_2
local R_bamboo_2_2 = cc.Sprite:create("Default/Sprite.png")
R_bamboo_2_2:setName("R_bamboo_2_2")
R_bamboo_2_2:setTag(9)
R_bamboo_2_2:setCascadeColorEnabled(true)
R_bamboo_2_2:setCascadeOpacityEnabled(true)
R_bamboo_2_2:setVisible(false)
R_bamboo_2_2:setPosition(-333.0000, -85.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(R_bamboo_2_2)
layout:setSize({width = 46.0000, height = 46.0000})
layout:setLeftMargin(-356.0000)
layout:setRightMargin(310.0000)
layout:setTopMargin(62.0000)
layout:setBottomMargin(-108.0000)
R_bamboo_2_2:setBlendFunc({src = 1, dst = 771})
Node:addChild(R_bamboo_2_2)

--Create txt_remaind_card
local txt_remaind_card = ccui.TextAtlas:create([[70]],
													"Default/TextAtlas.png",
													14,
													20,
													"0")
txt_remaind_card:setLayoutComponentEnabled(true)
txt_remaind_card:setName("txt_remaind_card")
txt_remaind_card:setTag(1640)
txt_remaind_card:setCascadeColorEnabled(true)
txt_remaind_card:setCascadeOpacityEnabled(true)
txt_remaind_card:setVisible(false)
txt_remaind_card:setAnchorPoint(0.0000, 0.4590)
txt_remaind_card:setPosition(78.8406, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(txt_remaind_card)
layout:setSize({width = 0.0000, height = 20.0000})
layout:setLeftMargin(78.8406)
layout:setRightMargin(-78.8406)
layout:setTopMargin(-10.8200)
layout:setBottomMargin(-9.1800)
Node:addChild(txt_remaind_card)

--Create remain_card_icon
local remain_card_icon = cc.Sprite:create("Default/Sprite.png")
remain_card_icon:setName("remain_card_icon")
remain_card_icon:setTag(1641)
remain_card_icon:setCascadeColorEnabled(true)
remain_card_icon:setCascadeOpacityEnabled(true)
remain_card_icon:setVisible(false)
remain_card_icon:setPosition(64.7755, 0.3752)
layout = ccui.LayoutComponent:bindLayoutComponent(remain_card_icon)
layout:setSize({width = 46.0000, height = 46.0000})
layout:setLeftMargin(41.7755)
layout:setRightMargin(-87.7755)
layout:setTopMargin(-23.3752)
layout:setBottomMargin(-22.6248)
remain_card_icon:setBlendFunc({src = 1, dst = 771})
Node:addChild(remain_card_icon)

--Create delay_time
local delay_time = ccui.Text:create()
delay_time:ignoreContentAdaptWithSize(true)
delay_time:setTextAreaSize({width = 0, height = 0})
delay_time:setFontSize(12)
delay_time:setString([[0ms]])
delay_time:setLayoutComponentEnabled(true)
delay_time:setName("delay_time")
delay_time:setTag(279)
delay_time:setCascadeColorEnabled(true)
delay_time:setCascadeOpacityEnabled(true)
delay_time:setPosition(-67.9992, -11.0000)
delay_time:setTextColor({r = 14, g = 244, b = 34})
layout = ccui.LayoutComponent:bindLayoutComponent(delay_time)
layout:setSize({width = 18.0000, height = 12.0000})
layout:setLeftMargin(-76.9992)
layout:setRightMargin(58.9992)
layout:setTopMargin(5.0000)
layout:setBottomMargin(-17.0000)
Node:addChild(delay_time)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

