--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create Panel_split
local Panel_split = ccui.Layout:create()
Panel_split:ignoreContentAdaptWithSize(false)
Panel_split:setClippingEnabled(false)
Panel_split:setBackGroundColorOpacity(102)
Panel_split:setTouchEnabled(true);
Panel_split:setLayoutComponentEnabled(true)
Panel_split:setName("Panel_split")
Panel_split:setTag(71)
Panel_split:setCascadeColorEnabled(true)
Panel_split:setCascadeOpacityEnabled(true)
Panel_split:setAnchorPoint(0.5000, 0.5000)
Panel_split:setPosition(640.0000, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_split)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
Layer:addChild(Panel_split)

--Create Panel_title
local Panel_title = ccui.Layout:create()
Panel_title:ignoreContentAdaptWithSize(false)
Panel_title:setClippingEnabled(false)
Panel_title:setBackGroundColorOpacity(102)
Panel_title:setTouchEnabled(true);
Panel_title:setLayoutComponentEnabled(true)
Panel_title:setName("Panel_title")
Panel_title:setTag(18)
Panel_title:setCascadeColorEnabled(true)
Panel_title:setCascadeOpacityEnabled(true)
Panel_title:setAnchorPoint(0.5000, 0.5000)
Panel_title:setPosition(640.0000, 510.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_title)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.7083)
layout:setPercentWidth(0.1563)
layout:setPercentHeight(0.2778)
layout:setSize({width = 200.0000, height = 200.0000})
layout:setLeftMargin(540.0000)
layout:setRightMargin(540.0000)
layout:setTopMargin(110.0000)
layout:setBottomMargin(410.0000)
Panel_split:addChild(Panel_title)

--Create Image_tiitle
local Image_tiitle = ccui.ImageView:create()
Image_tiitle:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/rewardtips/res/rewardtips_picture.plist")
Image_tiitle:loadTexture("app/part/xymj/rewardtips/res/rec_wenzi.png",1)
Image_tiitle:setLayoutComponentEnabled(true)
Image_tiitle:setName("Image_tiitle")
Image_tiitle:setTag(73)
Image_tiitle:setCascadeColorEnabled(true)
Image_tiitle:setCascadeOpacityEnabled(true)
Image_tiitle:setVisible(false)
Image_tiitle:setPosition(100.0000, 100.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_tiitle)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.1650)
layout:setPercentHeight(0.3400)
layout:setSize({width = 233.0000, height = 68.0000})
layout:setLeftMargin(-16.5000)
layout:setRightMargin(-16.5000)
layout:setTopMargin(66.0000)
layout:setBottomMargin(66.0000)
Panel_title:addChild(Image_tiitle)

--Create Image_title2
local Image_title2 = ccui.ImageView:create()
Image_title2:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/rewardtips/res/rewardtips_picture.plist")
Image_title2:loadTexture("app/part/xymj/rewardtips/res/fetch_wenzi.png",1)
Image_title2:setLayoutComponentEnabled(true)
Image_title2:setName("Image_title2")
Image_title2:setTag(19)
Image_title2:setCascadeColorEnabled(true)
Image_title2:setCascadeOpacityEnabled(true)
Image_title2:setPosition(100.0000, 100.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_title2)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.5000)
layout:setPercentHeight(0.1800)
layout:setSize({width = 300.0000, height = 36.0000})
layout:setLeftMargin(-50.0000)
layout:setRightMargin(-50.0000)
layout:setTopMargin(82.0000)
layout:setBottomMargin(82.0000)
Panel_title:addChild(Image_title2)

--Create Text_reward
local Text_reward = ccui.Text:create()
Text_reward:ignoreContentAdaptWithSize(true)
Text_reward:setTextAreaSize({width = 0, height = 0})
Text_reward:setFontName("font/msyh.ttf")
Text_reward:setFontSize(36)
Text_reward:setString([[钻石]])
Text_reward:enableOutline({r = 0, g = 0, b = 0, a = 255}, 2)
Text_reward:setLayoutComponentEnabled(true)
Text_reward:setName("Text_reward")
Text_reward:setTag(20)
Text_reward:setCascadeColorEnabled(true)
Text_reward:setCascadeOpacityEnabled(true)
Text_reward:setPosition(182.0000, 15.0000)
Text_reward:setTextColor({r = 210, g = 255, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_reward)
layout:setPositionPercentX(0.6067)
layout:setPositionPercentY(0.4167)
layout:setPercentWidth(0.2533)
layout:setPercentHeight(1.5000)
layout:setSize({width = 76.0000, height = 54.0000})
layout:setLeftMargin(144.0000)
layout:setRightMargin(80.0000)
layout:setTopMargin(-6.0000)
layout:setBottomMargin(-12.0000)
Image_title2:addChild(Text_reward)

--Create Image_rewarditem
local Image_rewarditem = ccui.ImageView:create()
Image_rewarditem:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/rewardtips/res/rewardtips_picture.plist")
Image_rewarditem:loadTexture("app/part/xymj/rewardtips/res/icon_dimand.png",1)
Image_rewarditem:setLayoutComponentEnabled(true)
Image_rewarditem:setName("Image_rewarditem")
Image_rewarditem:setTag(88)
Image_rewarditem:setCascadeColorEnabled(true)
Image_rewarditem:setCascadeOpacityEnabled(true)
Image_rewarditem:setPosition(640.0000, 370.0000)
Image_rewarditem:setScaleX(1.2000)
Image_rewarditem:setScaleY(1.2000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_rewarditem)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5139)
layout:setPercentWidth(0.0625)
layout:setPercentHeight(0.0986)
layout:setSize({width = 80.0000, height = 71.0000})
layout:setLeftMargin(600.0000)
layout:setRightMargin(600.0000)
layout:setTopMargin(314.5000)
layout:setBottomMargin(334.5000)
Panel_split:addChild(Image_rewarditem)

--Create Image_rewardblame
local Image_rewardblame = ccui.ImageView:create()
Image_rewardblame:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/rewardtips/res/rewardtips_picture.plist")
Image_rewardblame:loadTexture("app/part/xymj/rewardtips/res/blame.png",1)
Image_rewardblame:setLayoutComponentEnabled(true)
Image_rewardblame:setName("Image_rewardblame")
Image_rewardblame:setTag(77)
Image_rewardblame:setCascadeColorEnabled(true)
Image_rewardblame:setCascadeOpacityEnabled(true)
Image_rewardblame:setVisible(false)
Image_rewardblame:setPosition(640.0000, 370.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_rewardblame)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5139)
layout:setPercentWidth(0.0938)
layout:setPercentHeight(0.1750)
layout:setSize({width = 120.0000, height = 126.0000})
layout:setLeftMargin(580.0000)
layout:setRightMargin(580.0000)
layout:setTopMargin(287.0000)
layout:setBottomMargin(307.0000)
Panel_split:addChild(Image_rewardblame)

--Create Text_tips
local Text_tips = ccui.Text:create()
Text_tips:ignoreContentAdaptWithSize(false)
Text_tips:setFontName("font/msyh.ttf")
Text_tips:setFontSize(18)
Text_tips:setString([[请进入红包管理界面领取奖励]])
Text_tips:setTextHorizontalAlignment(1)
Text_tips:setLayoutComponentEnabled(true)
Text_tips:setName("Text_tips")
Text_tips:setTag(76)
Text_tips:setCascadeColorEnabled(true)
Text_tips:setCascadeOpacityEnabled(true)
Text_tips:setPosition(640.0000, 90.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_tips)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.1250)
layout:setPercentWidth(0.2500)
layout:setPercentHeight(0.1111)
layout:setSize({width = 320.0000, height = 80.0000})
layout:setLeftMargin(480.0000)
layout:setRightMargin(480.0000)
layout:setTopMargin(590.0000)
layout:setBottomMargin(50.0000)
Panel_split:addChild(Text_tips)

--Create AtlasLabel_num
local AtlasLabel_num = ccui.TextAtlas:create([[100]],
													"app/part/xymj/rewardtips/res/num.png",
													18,
													32,
													".")
AtlasLabel_num:setLayoutComponentEnabled(true)
AtlasLabel_num:setName("AtlasLabel_num")
AtlasLabel_num:setTag(81)
AtlasLabel_num:setCascadeColorEnabled(true)
AtlasLabel_num:setCascadeOpacityEnabled(true)
AtlasLabel_num:setPosition(640.0000, 270.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(AtlasLabel_num)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.3750)
layout:setPercentWidth(0.0422)
layout:setPercentHeight(0.0444)
layout:setSize({width = 54.0000, height = 32.0000})
layout:setLeftMargin(613.0000)
layout:setRightMargin(613.0000)
layout:setTopMargin(434.0000)
layout:setBottomMargin(254.0000)
Panel_split:addChild(AtlasLabel_num)

--Create Button_ok
local Button_ok = ccui.Button:create()
Button_ok:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/rewardtips/res/rewardtips_picture.plist")
Button_ok:loadTextureNormal("app/part/xymj/rewardtips/res/button.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/rewardtips/res/rewardtips_picture.plist")
Button_ok:loadTexturePressed("app/part/xymj/rewardtips/res/button.png",1)
Button_ok:loadTextureDisabled("Default/Button_Disable.png",0)
Button_ok:setTitleFontSize(14)
Button_ok:setTitleColor({r = 65, g = 65, b = 70})
Button_ok:setScale9Enabled(true)
Button_ok:setCapInsets({x = 15, y = 11, width = 186, height = 50})
Button_ok:setLayoutComponentEnabled(true)
Button_ok:setName("Button_ok")
Button_ok:setTag(79)
Button_ok:setCascadeColorEnabled(true)
Button_ok:setCascadeOpacityEnabled(true)
Button_ok:setPosition(640.0000, 170.0000)
if callBackProvider~=nil then
      Button_ok:addClickEventListener(callBackProvider("RewardTipsLayer-UI.lua", Button_ok, "ClickOk"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(Button_ok)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.2361)
layout:setPercentWidth(0.1688)
layout:setPercentHeight(0.1000)
layout:setSize({width = 216.0000, height = 72.0000})
layout:setLeftMargin(532.0000)
layout:setRightMargin(532.0000)
layout:setTopMargin(514.0000)
layout:setBottomMargin(134.0000)
Panel_split:addChild(Button_ok)

--Create Image_wenzi
local Image_wenzi = ccui.ImageView:create()
Image_wenzi:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/rewardtips/res/rewardtips_picture.plist")
Image_wenzi:loadTexture("app/part/xymj/rewardtips/res/open_wenzi.png",1)
Image_wenzi:setLayoutComponentEnabled(true)
Image_wenzi:setName("Image_wenzi")
Image_wenzi:setTag(80)
Image_wenzi:setCascadeColorEnabled(true)
Image_wenzi:setCascadeOpacityEnabled(true)
Image_wenzi:setPosition(108.0000, 40.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_wenzi)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5556)
layout:setPercentWidth(0.8194)
layout:setPercentHeight(0.5000)
layout:setSize({width = 177.0000, height = 36.0000})
layout:setLeftMargin(19.5000)
layout:setRightMargin(19.5000)
layout:setTopMargin(14.0000)
layout:setBottomMargin(22.0000)
Button_ok:addChild(Image_wenzi)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

