--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create bg
local bg = ccui.ImageView:create()
bg:ignoreContentAdaptWithSize(false)
bg:loadTexture("app/part/xymj/addroom/res/BackBoard.png",0)
bg:setLayoutComponentEnabled(true)
bg:setName("bg")
bg:setTag(78)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setPosition(640.0000, 362.0160)
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5028)
layout:setPercentWidth(0.4781)
layout:setPercentHeight(0.8667)
layout:setSize({width = 612.0000, height = 624.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(334.0000)
layout:setRightMargin(334.0000)
layout:setTopMargin(45.9840)
layout:setBottomMargin(50.0160)
Layer:addChild(bg)

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:loadTexture("app/part/xymj/addroom/res/foreg.png",0)
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(80)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setPosition(306.0000, 310.5024)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4976)
layout:setPercentWidth(0.9804)
layout:setPercentHeight(0.9760)
layout:setSize({width = 600.0000, height = 609.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(6.0000)
layout:setRightMargin(6.0000)
layout:setTopMargin(8.9976)
layout:setBottomMargin(6.0024)
bg:addChild(Image_1)

--Create title_bg
local title_bg = ccui.ImageView:create()
title_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/addroom/res/imboard_picture.plist")
title_bg:loadTexture("app/part/xymj/addroom/res/tipBg.png",1)
title_bg:setLayoutComponentEnabled(true)
title_bg:setName("title_bg")
title_bg:setTag(34)
title_bg:setCascadeColorEnabled(true)
title_bg:setCascadeOpacityEnabled(true)
title_bg:setPosition(306.0000, 591.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(title_bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.9471)
layout:setPercentWidth(0.9248)
layout:setPercentHeight(0.1683)
layout:setSize({width = 566.0000, height = 105.0000})
layout:setLeftMargin(23.0000)
layout:setRightMargin(23.0000)
layout:setTopMargin(-19.5000)
layout:setBottomMargin(538.5000)
bg:addChild(title_bg)

--Create tip_bg
local tip_bg = ccui.ImageView:create()
tip_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/addroom/res/imboard_picture.plist")
tip_bg:loadTexture("app/part/xymj/addroom/res/addgame_bg.png",1)
tip_bg:setLayoutComponentEnabled(true)
tip_bg:setName("tip_bg")
tip_bg:setTag(35)
tip_bg:setCascadeColorEnabled(true)
tip_bg:setCascadeOpacityEnabled(true)
tip_bg:setPosition(283.0000, 59.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(tip_bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5619)
layout:setPercentWidth(0.5318)
layout:setPercentHeight(0.4476)
layout:setSize({width = 301.0000, height = 47.0000})
layout:setLeftMargin(132.5000)
layout:setRightMargin(132.5000)
layout:setTopMargin(22.5000)
layout:setBottomMargin(35.5000)
title_bg:addChild(tip_bg)

--Create im_board
local im_board = ccui.ListView:create()
im_board:setItemsMargin(18)
im_board:setDirection(1)
im_board:setGravity(0)
im_board:ignoreContentAdaptWithSize(false)
im_board:setClippingEnabled(false)
im_board:setBackGroundColorOpacity(102)
im_board:setTouchEnabled(false);
im_board:setLayoutComponentEnabled(true)
im_board:setName("im_board")
im_board:setTag(90)
im_board:setCascadeColorEnabled(true)
im_board:setCascadeOpacityEnabled(true)
im_board:setPosition(53.0000, 59.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(im_board)
layout:setPositionPercentX(0.0866)
layout:setPositionPercentY(0.0946)
layout:setPercentWidth(0.8268)
layout:setPercentHeight(0.6250)
layout:setSize({width = 506.0000, height = 390.0000})
layout:setLeftMargin(53.0000)
layout:setRightMargin(53.0000)
layout:setTopMargin(175.0000)
layout:setBottomMargin(59.0000)
bg:addChild(im_board)

--Create im_1
local im_1 = ccui.Layout:create()
im_1:ignoreContentAdaptWithSize(false)
im_1:setClippingEnabled(false)
im_1:setBackGroundColorOpacity(102)
im_1:setTouchEnabled(true);
im_1:setLayoutComponentEnabled(true)
im_1:setName("im_1")
im_1:setTag(91)
im_1:setCascadeColorEnabled(true)
im_1:setCascadeOpacityEnabled(true)
im_1:setPosition(0.0000, 324.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(im_1)
layout:setPositionPercentY(0.7826)
layout:setPercentWidth(1.4229)
layout:setPercentHeight(0.2174)
layout:setSize({width = 720.0000, height = 90.0000})
layout:setRightMargin(-214.0000)
layout:setBottomMargin(324.0000)
im_board:pushBackCustomItem(im_1)

--Create num0
local num0 = ccui.Button:create()
num0:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/addroom/res/imboard_picture.plist")
num0:loadTextureNormal("app/part/xymj/addroom/res/btn1.png",1)
num0:loadTextureDisabled("Default/Button_Disable.png",0)
num0:setTitleFontSize(40)
num0:setTitleColor({r = 65, g = 65, b = 70})
num0:setScale9Enabled(true)
num0:setCapInsets({x = 15, y = 11, width = 123, height = 67})
num0:setLayoutComponentEnabled(true)
num0:setName("num0")
num0:setTag(80)
num0:setCascadeColorEnabled(true)
num0:setCascadeOpacityEnabled(true)
num0:setPosition(75.0000, 48.0000)
if callBackProvider~=nil then
      num0:addClickEventListener(callBackProvider("AddRoomLayer-UI.lua", num0, "NumClick1"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(num0)
layout:setPositionPercentX(0.1042)
layout:setPositionPercentY(0.5333)
layout:setPercentWidth(0.2125)
layout:setPercentHeight(0.9889)
layout:setSize({width = 153.0000, height = 89.0000})
layout:setLeftMargin(-1.5000)
layout:setRightMargin(568.5000)
layout:setTopMargin(-2.5000)
layout:setBottomMargin(3.5000)
im_1:addChild(num0)

--Create input_txt
local input_txt = ccui.TextAtlas:create([[1]],
													"app/part/xymj/addroom/res/number3.png",
													24,
													33,
													"0")
input_txt:setLayoutComponentEnabled(true)
input_txt:setName("input_txt")
input_txt:setTag(84)
input_txt:setCascadeColorEnabled(true)
input_txt:setCascadeOpacityEnabled(true)
input_txt:setPosition(76.5000, 44.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(input_txt)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.1569)
layout:setPercentHeight(0.3708)
layout:setSize({width = 24.0000, height = 33.0000})
layout:setLeftMargin(64.5000)
layout:setRightMargin(64.5000)
layout:setTopMargin(28.0000)
layout:setBottomMargin(28.0000)
num0:addChild(input_txt)

--Create num1
local num1 = ccui.Button:create()
num1:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/addroom/res/imboard_picture.plist")
num1:loadTextureNormal("app/part/xymj/addroom/res/btn1.png",1)
num1:loadTextureDisabled("Default/Button_Disable.png",0)
num1:setTitleFontSize(40)
num1:setTitleColor({r = 65, g = 65, b = 70})
num1:setScale9Enabled(true)
num1:setCapInsets({x = 15, y = 11, width = 123, height = 67})
num1:setLayoutComponentEnabled(true)
num1:setName("num1")
num1:setTag(81)
num1:setCascadeColorEnabled(true)
num1:setCascadeOpacityEnabled(true)
num1:setPosition(251.9459, 48.0000)
if callBackProvider~=nil then
      num1:addClickEventListener(callBackProvider("AddRoomLayer-UI.lua", num1, "NumClick2"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(num1)
layout:setPositionPercentX(0.3499)
layout:setPositionPercentY(0.5333)
layout:setPercentWidth(0.2125)
layout:setPercentHeight(0.9889)
layout:setSize({width = 153.0000, height = 89.0000})
layout:setLeftMargin(175.4459)
layout:setRightMargin(391.5541)
layout:setTopMargin(-2.5000)
layout:setBottomMargin(3.5000)
im_1:addChild(num1)

--Create input_txt
local input_txt = ccui.TextAtlas:create([[2]],
													"app/part/xymj/addroom/res/number3.png",
													24,
													33,
													"0")
input_txt:setLayoutComponentEnabled(true)
input_txt:setName("input_txt")
input_txt:setTag(85)
input_txt:setCascadeColorEnabled(true)
input_txt:setCascadeOpacityEnabled(true)
input_txt:setPosition(76.5000, 44.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(input_txt)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.1569)
layout:setPercentHeight(0.3708)
layout:setSize({width = 24.0000, height = 33.0000})
layout:setLeftMargin(64.5000)
layout:setRightMargin(64.5000)
layout:setTopMargin(28.0000)
layout:setBottomMargin(28.0000)
num1:addChild(input_txt)

--Create num2
local num2 = ccui.Button:create()
num2:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/addroom/res/imboard_picture.plist")
num2:loadTextureNormal("app/part/xymj/addroom/res/btn1.png",1)
num2:loadTextureDisabled("Default/Button_Disable.png",0)
num2:setTitleFontSize(40)
num2:setTitleColor({r = 65, g = 65, b = 70})
num2:setScale9Enabled(true)
num2:setCapInsets({x = 15, y = 11, width = 123, height = 67})
num2:setLayoutComponentEnabled(true)
num2:setName("num2")
num2:setTag(82)
num2:setCascadeColorEnabled(true)
num2:setCascadeOpacityEnabled(true)
num2:setPosition(427.0000, 48.0000)
if callBackProvider~=nil then
      num2:addClickEventListener(callBackProvider("AddRoomLayer-UI.lua", num2, "NumClick3"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(num2)
layout:setPositionPercentX(0.5931)
layout:setPositionPercentY(0.5333)
layout:setPercentWidth(0.2125)
layout:setPercentHeight(0.9889)
layout:setSize({width = 153.0000, height = 89.0000})
layout:setLeftMargin(350.5000)
layout:setRightMargin(216.5000)
layout:setTopMargin(-2.5000)
layout:setBottomMargin(3.5000)
im_1:addChild(num2)

--Create input_txt
local input_txt = ccui.TextAtlas:create([[3]],
													"app/part/xymj/addroom/res/number3.png",
													24,
													33,
													"0")
input_txt:setLayoutComponentEnabled(true)
input_txt:setName("input_txt")
input_txt:setTag(86)
input_txt:setCascadeColorEnabled(true)
input_txt:setCascadeOpacityEnabled(true)
input_txt:setPosition(76.5000, 44.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(input_txt)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.1569)
layout:setPercentHeight(0.3708)
layout:setSize({width = 24.0000, height = 33.0000})
layout:setLeftMargin(64.5000)
layout:setRightMargin(64.5000)
layout:setTopMargin(28.0000)
layout:setBottomMargin(28.0000)
num2:addChild(input_txt)

--Create im_2
local im_2 = ccui.Layout:create()
im_2:ignoreContentAdaptWithSize(false)
im_2:setClippingEnabled(false)
im_2:setBackGroundColorOpacity(102)
im_2:setTouchEnabled(true);
im_2:setLayoutComponentEnabled(true)
im_2:setName("im_2")
im_2:setLocalZOrder(1)
im_2:setTag(92)
im_2:setCascadeColorEnabled(true)
im_2:setCascadeOpacityEnabled(true)
im_2:setPosition(0.0000, 216.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(im_2)
layout:setPositionPercentY(0.5217)
layout:setPercentWidth(1.4229)
layout:setPercentHeight(0.2174)
layout:setSize({width = 720.0000, height = 90.0000})
layout:setRightMargin(-214.0000)
layout:setTopMargin(108.0000)
layout:setBottomMargin(216.0000)
im_board:pushBackCustomItem(im_2)

--Create num0
local num0 = ccui.Button:create()
num0:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/addroom/res/imboard_picture.plist")
num0:loadTextureNormal("app/part/xymj/addroom/res/btn1.png",1)
num0:loadTextureDisabled("Default/Button_Disable.png",0)
num0:setTitleFontSize(40)
num0:setTitleColor({r = 65, g = 65, b = 70})
num0:setScale9Enabled(true)
num0:setCapInsets({x = 15, y = 11, width = 123, height = 67})
num0:setLayoutComponentEnabled(true)
num0:setName("num0")
num0:setTag(93)
num0:setCascadeColorEnabled(true)
num0:setCascadeOpacityEnabled(true)
num0:setPosition(75.0000, 48.0000)
if callBackProvider~=nil then
      num0:addClickEventListener(callBackProvider("AddRoomLayer-UI.lua", num0, "NumClick4"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(num0)
layout:setPositionPercentX(0.1042)
layout:setPositionPercentY(0.5333)
layout:setPercentWidth(0.2125)
layout:setPercentHeight(0.9889)
layout:setSize({width = 153.0000, height = 89.0000})
layout:setLeftMargin(-1.5000)
layout:setRightMargin(568.5000)
layout:setTopMargin(-2.5000)
layout:setBottomMargin(3.5000)
im_2:addChild(num0)

--Create input_txt
local input_txt = ccui.TextAtlas:create([[4]],
													"app/part/xymj/addroom/res/number3.png",
													24,
													33,
													"0")
input_txt:setLayoutComponentEnabled(true)
input_txt:setName("input_txt")
input_txt:setTag(87)
input_txt:setCascadeColorEnabled(true)
input_txt:setCascadeOpacityEnabled(true)
input_txt:setPosition(76.5000, 44.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(input_txt)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.1569)
layout:setPercentHeight(0.3708)
layout:setSize({width = 24.0000, height = 33.0000})
layout:setLeftMargin(64.5000)
layout:setRightMargin(64.5000)
layout:setTopMargin(28.0000)
layout:setBottomMargin(28.0000)
num0:addChild(input_txt)

--Create num1
local num1 = ccui.Button:create()
num1:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/addroom/res/imboard_picture.plist")
num1:loadTextureNormal("app/part/xymj/addroom/res/btn1.png",1)
num1:loadTextureDisabled("Default/Button_Disable.png",0)
num1:setTitleFontSize(40)
num1:setTitleColor({r = 65, g = 65, b = 70})
num1:setScale9Enabled(true)
num1:setCapInsets({x = 15, y = 11, width = 123, height = 67})
num1:setLayoutComponentEnabled(true)
num1:setName("num1")
num1:setTag(94)
num1:setCascadeColorEnabled(true)
num1:setCascadeOpacityEnabled(true)
num1:setPosition(251.0000, 48.0000)
if callBackProvider~=nil then
      num1:addClickEventListener(callBackProvider("AddRoomLayer-UI.lua", num1, "NumClick5"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(num1)
layout:setPositionPercentX(0.3486)
layout:setPositionPercentY(0.5333)
layout:setPercentWidth(0.2125)
layout:setPercentHeight(0.9889)
layout:setSize({width = 153.0000, height = 89.0000})
layout:setLeftMargin(174.5000)
layout:setRightMargin(392.5000)
layout:setTopMargin(-2.5000)
layout:setBottomMargin(3.5000)
im_2:addChild(num1)

--Create input_txt
local input_txt = ccui.TextAtlas:create([[5]],
													"app/part/xymj/addroom/res/number3.png",
													24,
													33,
													"0")
input_txt:setLayoutComponentEnabled(true)
input_txt:setName("input_txt")
input_txt:setTag(88)
input_txt:setCascadeColorEnabled(true)
input_txt:setCascadeOpacityEnabled(true)
input_txt:setPosition(76.5000, 44.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(input_txt)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.1569)
layout:setPercentHeight(0.3708)
layout:setSize({width = 24.0000, height = 33.0000})
layout:setLeftMargin(64.5000)
layout:setRightMargin(64.5000)
layout:setTopMargin(28.0000)
layout:setBottomMargin(28.0000)
num1:addChild(input_txt)

--Create num2
local num2 = ccui.Button:create()
num2:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/addroom/res/imboard_picture.plist")
num2:loadTextureNormal("app/part/xymj/addroom/res/btn1.png",1)
num2:loadTextureDisabled("Default/Button_Disable.png",0)
num2:setTitleFontSize(40)
num2:setTitleColor({r = 65, g = 65, b = 70})
num2:setScale9Enabled(true)
num2:setCapInsets({x = 15, y = 11, width = 123, height = 67})
num2:setLayoutComponentEnabled(true)
num2:setName("num2")
num2:setTag(95)
num2:setCascadeColorEnabled(true)
num2:setCascadeOpacityEnabled(true)
num2:setPosition(427.0000, 48.0000)
if callBackProvider~=nil then
      num2:addClickEventListener(callBackProvider("AddRoomLayer-UI.lua", num2, "NumClick6"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(num2)
layout:setPositionPercentX(0.5931)
layout:setPositionPercentY(0.5333)
layout:setPercentWidth(0.2125)
layout:setPercentHeight(0.9889)
layout:setSize({width = 153.0000, height = 89.0000})
layout:setLeftMargin(350.5000)
layout:setRightMargin(216.5000)
layout:setTopMargin(-2.5000)
layout:setBottomMargin(3.5000)
im_2:addChild(num2)

--Create input_txt
local input_txt = ccui.TextAtlas:create([[6]],
													"app/part/xymj/addroom/res/number3.png",
													24,
													33,
													"0")
input_txt:setLayoutComponentEnabled(true)
input_txt:setName("input_txt")
input_txt:setTag(89)
input_txt:setCascadeColorEnabled(true)
input_txt:setCascadeOpacityEnabled(true)
input_txt:setPosition(76.5000, 44.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(input_txt)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.1569)
layout:setPercentHeight(0.3708)
layout:setSize({width = 24.0000, height = 33.0000})
layout:setLeftMargin(64.5000)
layout:setRightMargin(64.5000)
layout:setTopMargin(28.0000)
layout:setBottomMargin(28.0000)
num2:addChild(input_txt)

--Create im_3
local im_3 = ccui.Layout:create()
im_3:ignoreContentAdaptWithSize(false)
im_3:setClippingEnabled(false)
im_3:setBackGroundColorOpacity(102)
im_3:setTouchEnabled(true);
im_3:setLayoutComponentEnabled(true)
im_3:setName("im_3")
im_3:setLocalZOrder(2)
im_3:setTag(96)
im_3:setCascadeColorEnabled(true)
im_3:setCascadeOpacityEnabled(true)
im_3:setPosition(0.0000, 108.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(im_3)
layout:setPositionPercentY(0.2609)
layout:setPercentWidth(1.4229)
layout:setPercentHeight(0.2174)
layout:setSize({width = 720.0000, height = 90.0000})
layout:setRightMargin(-214.0000)
layout:setTopMargin(216.0000)
layout:setBottomMargin(108.0000)
im_board:pushBackCustomItem(im_3)

--Create num0
local num0 = ccui.Button:create()
num0:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/addroom/res/imboard_picture.plist")
num0:loadTextureNormal("app/part/xymj/addroom/res/btn1.png",1)
num0:loadTextureDisabled("Default/Button_Disable.png",0)
num0:setTitleFontSize(40)
num0:setTitleColor({r = 65, g = 65, b = 70})
num0:setScale9Enabled(true)
num0:setCapInsets({x = 15, y = 11, width = 123, height = 67})
num0:setLayoutComponentEnabled(true)
num0:setName("num0")
num0:setTag(97)
num0:setCascadeColorEnabled(true)
num0:setCascadeOpacityEnabled(true)
num0:setPosition(75.0000, 48.0000)
if callBackProvider~=nil then
      num0:addClickEventListener(callBackProvider("AddRoomLayer-UI.lua", num0, "NumClick7"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(num0)
layout:setPositionPercentX(0.1042)
layout:setPositionPercentY(0.5333)
layout:setPercentWidth(0.2125)
layout:setPercentHeight(0.9889)
layout:setSize({width = 153.0000, height = 89.0000})
layout:setLeftMargin(-1.5000)
layout:setRightMargin(568.5000)
layout:setTopMargin(-2.5000)
layout:setBottomMargin(3.5000)
im_3:addChild(num0)

--Create input_txt
local input_txt = ccui.TextAtlas:create([[7]],
													"app/part/xymj/addroom/res/number3.png",
													24,
													33,
													"0")
input_txt:setLayoutComponentEnabled(true)
input_txt:setName("input_txt")
input_txt:setTag(90)
input_txt:setCascadeColorEnabled(true)
input_txt:setCascadeOpacityEnabled(true)
input_txt:setPosition(76.5000, 44.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(input_txt)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.1569)
layout:setPercentHeight(0.3708)
layout:setSize({width = 24.0000, height = 33.0000})
layout:setLeftMargin(64.5000)
layout:setRightMargin(64.5000)
layout:setTopMargin(28.0000)
layout:setBottomMargin(28.0000)
num0:addChild(input_txt)

--Create num1
local num1 = ccui.Button:create()
num1:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/addroom/res/imboard_picture.plist")
num1:loadTextureNormal("app/part/xymj/addroom/res/btn1.png",1)
num1:loadTextureDisabled("Default/Button_Disable.png",0)
num1:setTitleFontSize(40)
num1:setTitleColor({r = 65, g = 65, b = 70})
num1:setScale9Enabled(true)
num1:setCapInsets({x = 15, y = 11, width = 123, height = 67})
num1:setLayoutComponentEnabled(true)
num1:setName("num1")
num1:setTag(98)
num1:setCascadeColorEnabled(true)
num1:setCascadeOpacityEnabled(true)
num1:setPosition(251.0000, 48.0000)
if callBackProvider~=nil then
      num1:addClickEventListener(callBackProvider("AddRoomLayer-UI.lua", num1, "NumClick8"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(num1)
layout:setPositionPercentX(0.3486)
layout:setPositionPercentY(0.5333)
layout:setPercentWidth(0.2125)
layout:setPercentHeight(0.9889)
layout:setSize({width = 153.0000, height = 89.0000})
layout:setLeftMargin(174.5000)
layout:setRightMargin(392.5000)
layout:setTopMargin(-2.5000)
layout:setBottomMargin(3.5000)
im_3:addChild(num1)

--Create input_txt
local input_txt = ccui.TextAtlas:create([[8]],
													"app/part/xymj/addroom/res/number3.png",
													24,
													33,
													"0")
input_txt:setLayoutComponentEnabled(true)
input_txt:setName("input_txt")
input_txt:setTag(91)
input_txt:setCascadeColorEnabled(true)
input_txt:setCascadeOpacityEnabled(true)
input_txt:setPosition(76.5000, 44.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(input_txt)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.1569)
layout:setPercentHeight(0.3708)
layout:setSize({width = 24.0000, height = 33.0000})
layout:setLeftMargin(64.5000)
layout:setRightMargin(64.5000)
layout:setTopMargin(28.0000)
layout:setBottomMargin(28.0000)
num1:addChild(input_txt)

--Create num2
local num2 = ccui.Button:create()
num2:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/addroom/res/imboard_picture.plist")
num2:loadTextureNormal("app/part/xymj/addroom/res/btn1.png",1)
num2:loadTextureDisabled("Default/Button_Disable.png",0)
num2:setTitleFontSize(40)
num2:setTitleColor({r = 65, g = 65, b = 70})
num2:setScale9Enabled(true)
num2:setCapInsets({x = 15, y = 11, width = 123, height = 67})
num2:setLayoutComponentEnabled(true)
num2:setName("num2")
num2:setTag(99)
num2:setCascadeColorEnabled(true)
num2:setCascadeOpacityEnabled(true)
num2:setPosition(427.0000, 48.0000)
if callBackProvider~=nil then
      num2:addClickEventListener(callBackProvider("AddRoomLayer-UI.lua", num2, "NumClick9"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(num2)
layout:setPositionPercentX(0.5931)
layout:setPositionPercentY(0.5333)
layout:setPercentWidth(0.2125)
layout:setPercentHeight(0.9889)
layout:setSize({width = 153.0000, height = 89.0000})
layout:setLeftMargin(350.5000)
layout:setRightMargin(216.5000)
layout:setTopMargin(-2.5000)
layout:setBottomMargin(3.5000)
im_3:addChild(num2)

--Create input_txt
local input_txt = ccui.TextAtlas:create([[9]],
													"app/part/xymj/addroom/res/number3.png",
													24,
													33,
													"0")
input_txt:setLayoutComponentEnabled(true)
input_txt:setName("input_txt")
input_txt:setTag(92)
input_txt:setCascadeColorEnabled(true)
input_txt:setCascadeOpacityEnabled(true)
input_txt:setPosition(76.5000, 44.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(input_txt)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.1569)
layout:setPercentHeight(0.3708)
layout:setSize({width = 24.0000, height = 33.0000})
layout:setLeftMargin(64.5000)
layout:setRightMargin(64.5000)
layout:setTopMargin(28.0000)
layout:setBottomMargin(28.0000)
num2:addChild(input_txt)

--Create im_4
local im_4 = ccui.Layout:create()
im_4:ignoreContentAdaptWithSize(false)
im_4:setClippingEnabled(false)
im_4:setBackGroundColorOpacity(102)
im_4:setTouchEnabled(true);
im_4:setLayoutComponentEnabled(true)
im_4:setName("im_4")
im_4:setLocalZOrder(3)
im_4:setTag(100)
im_4:setCascadeColorEnabled(true)
im_4:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(im_4)
layout:setPercentWidth(1.4229)
layout:setPercentHeight(0.2174)
layout:setSize({width = 720.0000, height = 90.0000})
layout:setRightMargin(-214.0000)
layout:setTopMargin(324.0000)
im_board:pushBackCustomItem(im_4)

--Create num0
local num0 = ccui.Button:create()
num0:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/addroom/res/imboard_picture.plist")
num0:loadTextureNormal("app/part/xymj/addroom/res/btn1.png",1)
num0:loadTextureDisabled("Default/Button_Disable.png",0)
num0:setTitleFontSize(40)
num0:setTitleColor({r = 65, g = 65, b = 70})
num0:setScale9Enabled(true)
num0:setCapInsets({x = 15, y = 11, width = 123, height = 67})
num0:setLayoutComponentEnabled(true)
num0:setName("num0")
num0:setTag(101)
num0:setCascadeColorEnabled(true)
num0:setCascadeOpacityEnabled(true)
num0:setPosition(251.0000, 48.0000)
if callBackProvider~=nil then
      num0:addClickEventListener(callBackProvider("AddRoomLayer-UI.lua", num0, "NumClick0"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(num0)
layout:setPositionPercentX(0.3486)
layout:setPositionPercentY(0.5333)
layout:setPercentWidth(0.2125)
layout:setPercentHeight(0.9889)
layout:setSize({width = 153.0000, height = 89.0000})
layout:setLeftMargin(174.5000)
layout:setRightMargin(392.5000)
layout:setTopMargin(-2.5000)
layout:setBottomMargin(3.5000)
im_4:addChild(num0)

--Create input_txt
local input_txt = ccui.TextAtlas:create([[0]],
													"app/part/xymj/addroom/res/number3.png",
													24,
													33,
													"0")
input_txt:setLayoutComponentEnabled(true)
input_txt:setName("input_txt")
input_txt:setTag(93)
input_txt:setCascadeColorEnabled(true)
input_txt:setCascadeOpacityEnabled(true)
input_txt:setPosition(76.5000, 44.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(input_txt)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.1569)
layout:setPercentHeight(0.3708)
layout:setSize({width = 24.0000, height = 33.0000})
layout:setLeftMargin(64.5000)
layout:setRightMargin(64.5000)
layout:setTopMargin(28.0000)
layout:setBottomMargin(28.0000)
num0:addChild(input_txt)

--Create reset_btn
local reset_btn = ccui.Button:create()
reset_btn:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/addroom/res/imboard_picture.plist")
reset_btn:loadTextureNormal("app/part/xymj/addroom/res/reset_normal.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/addroom/res/imboard_picture.plist")
reset_btn:loadTexturePressed("app/part/xymj/addroom/res/reset_press.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/addroom/res/imboard_picture.plist")
reset_btn:loadTextureDisabled("app/part/xymj/addroom/res/reset_press.png",1)
reset_btn:setTitleFontSize(40)
reset_btn:setTitleColor({r = 65, g = 65, b = 70})
reset_btn:setScale9Enabled(true)
reset_btn:setCapInsets({x = 15, y = 11, width = 123, height = 67})
reset_btn:setLayoutComponentEnabled(true)
reset_btn:setName("reset_btn")
reset_btn:setTag(102)
reset_btn:setCascadeColorEnabled(true)
reset_btn:setCascadeOpacityEnabled(true)
reset_btn:setPosition(75.0000, 48.0000)
if callBackProvider~=nil then
      reset_btn:addClickEventListener(callBackProvider("AddRoomLayer-UI.lua", reset_btn, "ResetClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(reset_btn)
layout:setPositionPercentX(0.1042)
layout:setPositionPercentY(0.5333)
layout:setPercentWidth(0.2125)
layout:setPercentHeight(0.9889)
layout:setSize({width = 153.0000, height = 89.0000})
layout:setLeftMargin(-1.5000)
layout:setRightMargin(568.5000)
layout:setTopMargin(-2.5000)
layout:setBottomMargin(3.5000)
im_4:addChild(reset_btn)

--Create num2
local num2 = ccui.Button:create()
num2:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/addroom/res/imboard_picture.plist")
num2:loadTextureNormal("app/part/xymj/addroom/res/del_normal.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/addroom/res/imboard_picture.plist")
num2:loadTexturePressed("app/part/xymj/addroom/res/del_press.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/addroom/res/imboard_picture.plist")
num2:loadTextureDisabled("app/part/xymj/addroom/res/del_press.png",1)
num2:setTitleFontSize(40)
num2:setTitleColor({r = 65, g = 65, b = 70})
num2:setScale9Enabled(true)
num2:setCapInsets({x = 15, y = 11, width = 123, height = 67})
num2:setLayoutComponentEnabled(true)
num2:setName("num2")
num2:setTag(103)
num2:setCascadeColorEnabled(true)
num2:setCascadeOpacityEnabled(true)
num2:setPosition(427.0000, 48.0000)
if callBackProvider~=nil then
      num2:addClickEventListener(callBackProvider("AddRoomLayer-UI.lua", num2, "DelClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(num2)
layout:setPositionPercentX(0.5931)
layout:setPositionPercentY(0.5333)
layout:setPercentWidth(0.2125)
layout:setPercentHeight(0.9889)
layout:setSize({width = 153.0000, height = 89.0000})
layout:setLeftMargin(350.5000)
layout:setRightMargin(216.5000)
layout:setTopMargin(-2.5000)
layout:setBottomMargin(3.5000)
im_4:addChild(num2)

--Create Image_3
local Image_3 = ccui.ImageView:create()
Image_3:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/addroom/res/imboard_picture.plist")
Image_3:loadTexture("app/part/xymj/addroom/res/add_input_bg2.png",1)
Image_3:setScale9Enabled(true)
Image_3:setCapInsets({x = 20, y = 20, width = 462, height = 26})
Image_3:setLayoutComponentEnabled(true)
Image_3:setName("Image_3")
Image_3:setTag(36)
Image_3:setCascadeColorEnabled(true)
Image_3:setCascadeOpacityEnabled(true)
Image_3:setPosition(302.0000, 492.2874)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_3)
layout:setPositionPercentX(0.4935)
layout:setPositionPercentY(0.7889)
layout:setPercentWidth(0.8203)
layout:setPercentHeight(0.1058)
layout:setSize({width = 502.0000, height = 66.0000})
layout:setHorizontalEdge(1)
layout:setLeftMargin(51.0000)
layout:setRightMargin(59.0000)
layout:setTopMargin(98.7126)
layout:setBottomMargin(459.2874)
bg:addChild(Image_3)

--Create input_txt1
local input_txt1 = ccui.TextAtlas:create([[]],
													"app/part/xymj/addroom/res/number3.png",
													24,
													33,
													"0")
input_txt1:setLayoutComponentEnabled(true)
input_txt1:setName("input_txt1")
input_txt1:setTag(106)
input_txt1:setCascadeColorEnabled(true)
input_txt1:setCascadeOpacityEnabled(true)
input_txt1:setPosition(42.0235, 31.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(input_txt1)
layout:setPositionPercentX(0.0837)
layout:setPositionPercentY(0.4773)
layout:setLeftMargin(42.0235)
layout:setRightMargin(459.9765)
layout:setTopMargin(34.5000)
layout:setBottomMargin(31.5000)
Image_3:addChild(input_txt1)

--Create input_txt2
local input_txt2 = ccui.TextAtlas:create([[]],
													"app/part/xymj/addroom/res/number3.png",
													24,
													33,
													"0")
input_txt2:setLayoutComponentEnabled(true)
input_txt2:setName("input_txt2")
input_txt2:setTag(79)
input_txt2:setCascadeColorEnabled(true)
input_txt2:setCascadeOpacityEnabled(true)
input_txt2:setPosition(126.0000, 31.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(input_txt2)
layout:setPositionPercentX(0.2510)
layout:setPositionPercentY(0.4773)
layout:setLeftMargin(126.0000)
layout:setRightMargin(376.0000)
layout:setTopMargin(34.5000)
layout:setBottomMargin(31.5000)
Image_3:addChild(input_txt2)

--Create input_txt3
local input_txt3 = ccui.TextAtlas:create([[]],
													"app/part/xymj/addroom/res/number3.png",
													24,
													33,
													"0")
input_txt3:setLayoutComponentEnabled(true)
input_txt3:setName("input_txt3")
input_txt3:setTag(80)
input_txt3:setCascadeColorEnabled(true)
input_txt3:setCascadeOpacityEnabled(true)
input_txt3:setPosition(210.0000, 31.5000)
input_txt3:setScaleX(0.9352)
layout = ccui.LayoutComponent:bindLayoutComponent(input_txt3)
layout:setPositionPercentX(0.4183)
layout:setPositionPercentY(0.4773)
layout:setLeftMargin(210.0000)
layout:setRightMargin(292.0000)
layout:setTopMargin(34.5000)
layout:setBottomMargin(31.5000)
Image_3:addChild(input_txt3)

--Create input_txt4
local input_txt4 = ccui.TextAtlas:create([[]],
													"app/part/xymj/addroom/res/number3.png",
													24,
													33,
													"0")
input_txt4:setLayoutComponentEnabled(true)
input_txt4:setName("input_txt4")
input_txt4:setTag(81)
input_txt4:setCascadeColorEnabled(true)
input_txt4:setCascadeOpacityEnabled(true)
input_txt4:setPosition(294.0000, 31.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(input_txt4)
layout:setPositionPercentX(0.5857)
layout:setPositionPercentY(0.4773)
layout:setLeftMargin(294.0000)
layout:setRightMargin(208.0000)
layout:setTopMargin(34.5000)
layout:setBottomMargin(31.5000)
Image_3:addChild(input_txt4)

--Create input_txt5
local input_txt5 = ccui.TextAtlas:create([[]],
													"app/part/xymj/addroom/res/number3.png",
													24,
													33,
													"0")
input_txt5:setLayoutComponentEnabled(true)
input_txt5:setName("input_txt5")
input_txt5:setTag(82)
input_txt5:setCascadeColorEnabled(true)
input_txt5:setCascadeOpacityEnabled(true)
input_txt5:setPosition(378.0000, 31.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(input_txt5)
layout:setPositionPercentX(0.7530)
layout:setPositionPercentY(0.4773)
layout:setLeftMargin(378.0000)
layout:setRightMargin(124.0000)
layout:setTopMargin(34.5000)
layout:setBottomMargin(31.5000)
Image_3:addChild(input_txt5)

--Create input_txt6
local input_txt6 = ccui.TextAtlas:create([[]],
													"app/part/xymj/addroom/res/number3.png",
													24,
													33,
													"0")
input_txt6:setLayoutComponentEnabled(true)
input_txt6:setName("input_txt6")
input_txt6:setTag(83)
input_txt6:setCascadeColorEnabled(true)
input_txt6:setCascadeOpacityEnabled(true)
input_txt6:setPosition(462.0000, 31.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(input_txt6)
layout:setPositionPercentX(0.9203)
layout:setPositionPercentY(0.4773)
layout:setLeftMargin(462.0000)
layout:setRightMargin(40.0000)
layout:setTopMargin(34.5000)
layout:setBottomMargin(31.5000)
Image_3:addChild(input_txt6)

--Create close_btn
local close_btn = ccui.Button:create()
close_btn:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/addroom/res/imboard_picture.plist")
close_btn:loadTextureNormal("app/part/xymj/addroom/res/close.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/addroom/res/imboard_picture.plist")
close_btn:loadTexturePressed("app/part/xymj/addroom/res/close.png",1)
close_btn:loadTextureDisabled("Default/Button_Disable.png",0)
close_btn:setTitleFontSize(14)
close_btn:setTitleColor({r = 65, g = 65, b = 70})
close_btn:setScale9Enabled(true)
close_btn:setCapInsets({x = 15, y = 11, width = 52, height = 60})
close_btn:setLayoutComponentEnabled(true)
close_btn:setName("close_btn")
close_btn:setTag(107)
close_btn:setCascadeColorEnabled(true)
close_btn:setCascadeOpacityEnabled(true)
close_btn:setPosition(602.4351, 609.7953)
if callBackProvider~=nil then
      close_btn:addClickEventListener(callBackProvider("AddRoomLayer-UI.lua", close_btn, "CloseClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(close_btn)
layout:setPositionPercentX(0.9844)
layout:setPositionPercentY(0.9772)
layout:setPercentWidth(0.1340)
layout:setPercentHeight(0.1314)
layout:setSize({width = 82.0000, height = 82.0000})
layout:setLeftMargin(561.4351)
layout:setRightMargin(-31.4351)
layout:setTopMargin(-26.7953)
layout:setBottomMargin(568.7953)
bg:addChild(close_btn)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

