--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create bg
local bg = ccui.ImageView:create()
bg:ignoreContentAdaptWithSize(false)
bg:loadTexture("app/part/xymj/newpayChoseTip/res/smallbg.png",0)
bg:setScale9Enabled(true)
bg:setCapInsets({x = 15, y = 15, width = 452, height = 258})
bg:setLayoutComponentEnabled(true)
bg:setName("bg")
bg:setTag(28)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setPosition(640.0000, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3766)
layout:setPercentHeight(0.4000)
layout:setSize({width = 482.0000, height = 288.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(399.0000)
layout:setRightMargin(399.0000)
layout:setTopMargin(216.0000)
layout:setBottomMargin(216.0000)
Layer:addChild(bg)

--Create info_bg
local info_bg = ccui.ImageView:create()
info_bg:ignoreContentAdaptWithSize(false)
info_bg:loadTexture("app/part/xymj/newpayChoseTip/res/scale9bg.png",0)
info_bg:setScale9Enabled(true)
info_bg:setCapInsets({x = 11, y = 12, width = 438, height = 245})
info_bg:setLayoutComponentEnabled(true)
info_bg:setName("info_bg")
info_bg:setTag(29)
info_bg:setCascadeColorEnabled(true)
info_bg:setCascadeOpacityEnabled(true)
info_bg:setPosition(241.0000, 144.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(info_bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.9544)
layout:setPercentHeight(0.9340)
layout:setSize({width = 460.0000, height = 269.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(11.0000)
layout:setRightMargin(11.0000)
layout:setTopMargin(9.5000)
layout:setBottomMargin(9.5000)
bg:addChild(info_bg)

--Create Text_1
local Text_1 = ccui.Text:create()
Text_1:ignoreContentAdaptWithSize(true)
Text_1:setTextAreaSize({width = 0, height = 0})
Text_1:setFontSize(34)
Text_1:setString([[请选择支付方式]])
Text_1:setTextHorizontalAlignment(1)
Text_1:setLayoutComponentEnabled(true)
Text_1:setName("Text_1")
Text_1:setTag(30)
Text_1:setCascadeColorEnabled(true)
Text_1:setCascadeOpacityEnabled(true)
Text_1:setPosition(225.4406, 172.5849)
Text_1:setTextColor({r = 106, g = 51, b = 10})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_1)
layout:setPositionPercentX(0.4901)
layout:setPositionPercentY(0.6416)
layout:setPercentWidth(0.5174)
layout:setPercentHeight(0.1264)
layout:setSize({width = 238.0000, height = 34.0000})
layout:setLeftMargin(106.4406)
layout:setRightMargin(115.5594)
layout:setTopMargin(79.4151)
layout:setBottomMargin(155.5849)
info_bg:addChild(Text_1)

--Create Button_7
local Button_7 = ccui.Button:create()
Button_7:ignoreContentAdaptWithSize(false)
Button_7:loadTextureNormal("app/part/xymj/newpayChoseTip/res/btn_close.png",0)
Button_7:loadTexturePressed("app/part/xymj/newpayChoseTip/res/btn_close.png",0)
Button_7:loadTextureDisabled("Default/Button_Disable.png",0)
Button_7:setTitleFontSize(14)
Button_7:setTitleColor({r = 65, g = 65, b = 70})
Button_7:setScale9Enabled(true)
Button_7:setCapInsets({x = 15, y = 11, width = 52, height = 60})
Button_7:setLayoutComponentEnabled(true)
Button_7:setName("Button_7")
Button_7:setTag(31)
Button_7:setCascadeColorEnabled(true)
Button_7:setCascadeOpacityEnabled(true)
Button_7:setPosition(478.3428, 278.7390)
if callBackProvider~=nil then
      Button_7:addClickEventListener(callBackProvider("PayChoseTipLayer-UI.lua", Button_7, "closeClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(Button_7)
layout:setPositionPercentX(0.9924)
layout:setPositionPercentY(0.9678)
layout:setPercentWidth(0.1701)
layout:setPercentHeight(0.2847)
layout:setSize({width = 82.0000, height = 82.0000})
layout:setLeftMargin(437.3428)
layout:setRightMargin(-37.3428)
layout:setTopMargin(-31.7390)
layout:setBottomMargin(237.7390)
bg:addChild(Button_7)

--Create Button_wx
local Button_wx = ccui.Button:create()
Button_wx:ignoreContentAdaptWithSize(false)
Button_wx:loadTextureNormal("app/part/xymj/newpayChoseTip/res/wxbg.png",0)
Button_wx:loadTexturePressed("app/part/xymj/newpayChoseTip/res/wxbgPress.png",0)
Button_wx:loadTextureDisabled("Default/Button_Disable.png",0)
Button_wx:setTitleFontSize(14)
Button_wx:setTitleColor({r = 65, g = 65, b = 70})
Button_wx:setScale9Enabled(true)
Button_wx:setCapInsets({x = 15, y = 11, width = 165, height = 43})
Button_wx:setLayoutComponentEnabled(true)
Button_wx:setName("Button_wx")
Button_wx:setTag(32)
Button_wx:setCascadeColorEnabled(true)
Button_wx:setCascadeOpacityEnabled(true)
Button_wx:setPosition(135.1369, 80.3529)
if callBackProvider~=nil then
      Button_wx:addClickEventListener(callBackProvider("PayChoseTipLayer-UI.lua", Button_wx, "WxPayClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(Button_wx)
layout:setPositionPercentX(0.2804)
layout:setPositionPercentY(0.2790)
layout:setPercentWidth(0.4046)
layout:setPercentHeight(0.2257)
layout:setSize({width = 195.0000, height = 65.0000})
layout:setLeftMargin(37.6369)
layout:setRightMargin(249.3631)
layout:setTopMargin(175.1471)
layout:setBottomMargin(47.8529)
bg:addChild(Button_wx)

--Create Image_10
local Image_10 = ccui.ImageView:create()
Image_10:ignoreContentAdaptWithSize(false)
Image_10:loadTexture("app/part/xymj/newpayChoseTip/res/wx.png",0)
Image_10:setLayoutComponentEnabled(true)
Image_10:setName("Image_10")
Image_10:setTag(33)
Image_10:setCascadeColorEnabled(true)
Image_10:setCascadeOpacityEnabled(true)
Image_10:setPosition(102.3269, 33.0190)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_10)
layout:setPositionPercentX(0.5248)
layout:setPositionPercentY(0.5080)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 195.0000, height = 65.0000})
layout:setLeftMargin(4.8269)
layout:setRightMargin(-4.8269)
layout:setTopMargin(-0.5190)
layout:setBottomMargin(0.5190)
Button_wx:addChild(Image_10)

--Create Button_aili
local Button_aili = ccui.Button:create()
Button_aili:ignoreContentAdaptWithSize(false)
Button_aili:loadTextureNormal("app/part/xymj/newpayChoseTip/res/zhifubaoBg.png",0)
Button_aili:loadTexturePressed("app/part/xymj/newpayChoseTip/res/zhifubaoBgPress.png",0)
Button_aili:loadTextureDisabled("Default/Button_Disable.png",0)
Button_aili:setTitleFontSize(14)
Button_aili:setTitleColor({r = 65, g = 65, b = 70})
Button_aili:setScale9Enabled(true)
Button_aili:setCapInsets({x = 15, y = 11, width = 165, height = 43})
Button_aili:setLayoutComponentEnabled(true)
Button_aili:setName("Button_aili")
Button_aili:setTag(34)
Button_aili:setCascadeColorEnabled(true)
Button_aili:setCascadeOpacityEnabled(true)
Button_aili:setPosition(346.4967, 81.7197)
if callBackProvider~=nil then
      Button_aili:addClickEventListener(callBackProvider("PayChoseTipLayer-UI.lua", Button_aili, "AiliPayClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(Button_aili)
layout:setPositionPercentX(0.7189)
layout:setPositionPercentY(0.2837)
layout:setPercentWidth(0.4046)
layout:setPercentHeight(0.2257)
layout:setSize({width = 195.0000, height = 65.0000})
layout:setLeftMargin(248.9967)
layout:setRightMargin(38.0033)
layout:setTopMargin(173.7803)
layout:setBottomMargin(49.2197)
bg:addChild(Button_aili)

--Create Image_10
local Image_10 = ccui.ImageView:create()
Image_10:ignoreContentAdaptWithSize(false)
Image_10:loadTexture("app/part/xymj/newpayChoseTip/res/zhifubao.png",0)
Image_10:setLayoutComponentEnabled(true)
Image_10:setName("Image_10")
Image_10:setTag(35)
Image_10:setCascadeColorEnabled(true)
Image_10:setCascadeOpacityEnabled(true)
Image_10:setPosition(101.2222, 33.0190)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_10)
layout:setPositionPercentX(0.5191)
layout:setPositionPercentY(0.5080)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 195.0000, height = 65.0000})
layout:setLeftMargin(3.7222)
layout:setRightMargin(-3.7222)
layout:setTopMargin(-0.5190)
layout:setBottomMargin(0.5190)
Button_aili:addChild(Image_10)

--Create touch_mask
local touch_mask = ccui.Button:create()
touch_mask:ignoreContentAdaptWithSize(false)
touch_mask:loadTextureDisabled("Default/Button_Disable.png",0)
touch_mask:setTitleFontSize(14)
touch_mask:setTitleColor({r = 65, g = 65, b = 70})
touch_mask:setScale9Enabled(true)
touch_mask:setCapInsets({x = -15, y = -4, width = 30, height = 8})
touch_mask:setTouchEnabled(false);
touch_mask:setLayoutComponentEnabled(true)
touch_mask:setName("touch_mask")
touch_mask:setTag(36)
touch_mask:setCascadeColorEnabled(true)
touch_mask:setCascadeOpacityEnabled(true)
touch_mask:setVisible(false)
touch_mask:setPosition(641.6639, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(touch_mask)
layout:setPositionPercentX(0.5013)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(1.6639)
layout:setRightMargin(-1.6639)
Layer:addChild(touch_mask)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

