--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create CheckBox_page
local CheckBox_page = ccui.CheckBox:create()
CheckBox_page:ignoreContentAdaptWithSize(false)
CheckBox_page:loadTextureBackGround("app/part/xymj/ad/res/point2.png",0)
CheckBox_page:loadTextureBackGroundSelected("app/part/xymj/ad/res/point2.png",0)
CheckBox_page:loadTextureBackGroundDisabled("Default/CheckBox_Disable.png",0)
CheckBox_page:loadTextureFrontCross("app/part/xymj/ad/res/point1.png",0)
CheckBox_page:loadTextureFrontCrossDisabled("app/part/xymj/ad/res/point1.png",0)
CheckBox_page:setSelected(true)
CheckBox_page:setLayoutComponentEnabled(true)
CheckBox_page:setName("CheckBox_page")
CheckBox_page:setTag(9)
CheckBox_page:setCascadeColorEnabled(true)
CheckBox_page:setCascadeOpacityEnabled(true)
CheckBox_page:setPosition(-432.6072, 287.7686)
layout = ccui.LayoutComponent:bindLayoutComponent(CheckBox_page)
layout:setSize({width = 12.0000, height = 13.0000})
layout:setLeftMargin(-438.6072)
layout:setRightMargin(426.6072)
layout:setTopMargin(-294.2686)
layout:setBottomMargin(281.2686)
Node:addChild(CheckBox_page)

--Create Ad_Panel
local Ad_Panel = ccui.Layout:create()
Ad_Panel:ignoreContentAdaptWithSize(false)
Ad_Panel:setClippingEnabled(false)
Ad_Panel:setBackGroundColorOpacity(102)
Ad_Panel:setTouchEnabled(true);
Ad_Panel:setLayoutComponentEnabled(true)
Ad_Panel:setName("Ad_Panel")
Ad_Panel:setTag(13)
Ad_Panel:setCascadeColorEnabled(true)
Ad_Panel:setCascadeOpacityEnabled(true)
Ad_Panel:setAnchorPoint(0.5000, 0.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Ad_Panel)
layout:setSize({width = 266.0000, height = 200.0000})
layout:setLeftMargin(-133.0000)
layout:setRightMargin(-133.0000)
layout:setTopMargin(-100.0000)
layout:setBottomMargin(-100.0000)
Node:addChild(Ad_Panel)

--Create Image_bg
local Image_bg = ccui.ImageView:create()
Image_bg:ignoreContentAdaptWithSize(false)
Image_bg:loadTexture("app/part/xymj/ad/res/adv_bkg.png",0)
Image_bg:setLayoutComponentEnabled(true)
Image_bg:setName("Image_bg")
Image_bg:setTag(8)
Image_bg:setCascadeColorEnabled(true)
Image_bg:setCascadeOpacityEnabled(true)
Image_bg:setPosition(133.0000, 100.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.1617)
layout:setPercentHeight(2.1450)
layout:setSize({width = 309.0000, height = 429.0000})
layout:setLeftMargin(-21.5000)
layout:setRightMargin(-21.5000)
layout:setTopMargin(-114.5000)
layout:setBottomMargin(-114.5000)
Ad_Panel:addChild(Image_bg)

--Create Ad_PageView
local Ad_PageView = ccui.PageView:create()
Ad_PageView:ignoreContentAdaptWithSize(false)
Ad_PageView:setClippingEnabled(true)
Ad_PageView:setBackGroundColorOpacity(102)
Ad_PageView:setLayoutComponentEnabled(true)
Ad_PageView:setName("Ad_PageView")
Ad_PageView:setTag(14)
Ad_PageView:setCascadeColorEnabled(true)
Ad_PageView:setCascadeOpacityEnabled(true)
Ad_PageView:setAnchorPoint(0.5000, 0.5000)
Ad_PageView:setPosition(132.9945, 100.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Ad_PageView)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.2331)
layout:setPercentHeight(2.2750)
layout:setSize({width = 328.0000, height = 455.0000})
layout:setLeftMargin(-31.0055)
layout:setRightMargin(-30.9945)
layout:setTopMargin(-127.5000)
layout:setBottomMargin(-127.5000)
Ad_Panel:addChild(Ad_PageView)

--Create Ad_Image_Panel
local Ad_Image_Panel = ccui.Layout:create()
Ad_Image_Panel:ignoreContentAdaptWithSize(false)
Ad_Image_Panel:setClippingEnabled(false)
Ad_Image_Panel:setBackGroundColorOpacity(102)
Ad_Image_Panel:setLayoutComponentEnabled(true)
Ad_Image_Panel:setName("Ad_Image_Panel")
Ad_Image_Panel:setTag(34)
Ad_Image_Panel:setCascadeColorEnabled(true)
Ad_Image_Panel:setCascadeOpacityEnabled(true)
Ad_Image_Panel:setPosition(-845.0000, 274.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Ad_Image_Panel)
layout:setSize({width = 328.0000, height = 455.0000})
layout:setLeftMargin(-845.0000)
layout:setRightMargin(517.0000)
layout:setTopMargin(-729.0000)
layout:setBottomMargin(274.0000)
Node:addChild(Ad_Image_Panel)

--Create Ad_Image
local Ad_Image = ccui.ImageView:create()
Ad_Image:ignoreContentAdaptWithSize(false)
Ad_Image:loadTexture("app/part/xymj/ad/res/AdPic.png",0)
Ad_Image:setLayoutComponentEnabled(true)
Ad_Image:setName("Ad_Image")
Ad_Image:setTag(100)
Ad_Image:setCascadeColorEnabled(true)
Ad_Image:setCascadeOpacityEnabled(true)
Ad_Image:setPosition(164.0000, 227.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Ad_Image)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.8567)
layout:setPercentHeight(0.8484)
layout:setSize({width = 281.0000, height = 386.0000})
layout:setLeftMargin(23.5000)
layout:setRightMargin(23.5000)
layout:setTopMargin(34.5000)
layout:setBottomMargin(34.5000)
Ad_Image_Panel:addChild(Ad_Image)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

