--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create touch_mask
local touch_mask = ccui.Button:create()
touch_mask:ignoreContentAdaptWithSize(false)
touch_mask:loadTextureDisabled("Default/Button_Disable.png",0)
touch_mask:setTitleFontSize(14)
touch_mask:setTitleColor({r = 65, g = 65, b = 70})
touch_mask:setScale9Enabled(true)
touch_mask:setCapInsets({x = -15, y = -4, width = 30, height = 8})
touch_mask:setLayoutComponentEnabled(true)
touch_mask:setName("touch_mask")
touch_mask:setTag(65)
touch_mask:setCascadeColorEnabled(true)
touch_mask:setCascadeOpacityEnabled(true)
touch_mask:setPosition(640.0000, 360.0000)
if callBackProvider~=nil then
      touch_mask:addClickEventListener(callBackProvider("NaozhuangLayer-UI.lua", touch_mask, "MaskClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(touch_mask)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
Layer:addChild(touch_mask)

--Create naozhuang_panel
local naozhuang_panel = ccui.Layout:create()
naozhuang_panel:ignoreContentAdaptWithSize(false)
naozhuang_panel:setClippingEnabled(false)
naozhuang_panel:setBackGroundColorOpacity(102)
naozhuang_panel:setTouchEnabled(true);
naozhuang_panel:setLayoutComponentEnabled(true)
naozhuang_panel:setName("naozhuang_panel")
naozhuang_panel:setTag(261)
naozhuang_panel:setCascadeColorEnabled(true)
naozhuang_panel:setCascadeOpacityEnabled(true)
naozhuang_panel:setAnchorPoint(0.5000, 0.5000)
naozhuang_panel:setPosition(640.0000, 391.0320)
layout = ccui.LayoutComponent:bindLayoutComponent(naozhuang_panel)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5431)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setTopMargin(-31.0320)
layout:setBottomMargin(31.0320)
Layer:addChild(naozhuang_panel)

--Create tip_wait_naozhuang_bg
local tip_wait_naozhuang_bg = ccui.ImageView:create()
tip_wait_naozhuang_bg:ignoreContentAdaptWithSize(false)
tip_wait_naozhuang_bg:loadTexture("app/part/xymj/naozhuang/res/naozhuang_tip_bg.png",0)
tip_wait_naozhuang_bg:setLayoutComponentEnabled(true)
tip_wait_naozhuang_bg:setName("tip_wait_naozhuang_bg")
tip_wait_naozhuang_bg:setTag(283)
tip_wait_naozhuang_bg:setCascadeColorEnabled(true)
tip_wait_naozhuang_bg:setCascadeOpacityEnabled(true)
tip_wait_naozhuang_bg:setPosition(640.0804, 331.3400)
layout = ccui.LayoutComponent:bindLayoutComponent(tip_wait_naozhuang_bg)
layout:setPositionPercentX(0.5001)
layout:setPositionPercentY(0.4602)
layout:setPercentWidth(0.4922)
layout:setPercentHeight(0.0944)
layout:setSize({width = 630.0000, height = 68.0000})
layout:setLeftMargin(325.0804)
layout:setRightMargin(324.9196)
layout:setTopMargin(354.6600)
layout:setBottomMargin(297.3400)
naozhuang_panel:addChild(tip_wait_naozhuang_bg)

--Create tip_wait_naozhuang
local tip_wait_naozhuang = ccui.ImageView:create()
tip_wait_naozhuang:ignoreContentAdaptWithSize(false)
tip_wait_naozhuang:loadTexture("app/part/xymj/naozhuang/res/wait_naozhuang_tip.png",0)
tip_wait_naozhuang:setLayoutComponentEnabled(true)
tip_wait_naozhuang:setName("tip_wait_naozhuang")
tip_wait_naozhuang:setTag(284)
tip_wait_naozhuang:setCascadeColorEnabled(true)
tip_wait_naozhuang:setCascadeOpacityEnabled(true)
tip_wait_naozhuang:setPosition(647.5774, 331.3400)
layout = ccui.LayoutComponent:bindLayoutComponent(tip_wait_naozhuang)
layout:setPositionPercentX(0.5059)
layout:setPositionPercentY(0.4602)
layout:setPercentWidth(0.2844)
layout:setPercentHeight(0.0444)
layout:setSize({width = 364.0000, height = 32.0000})
layout:setLeftMargin(465.5774)
layout:setRightMargin(450.4226)
layout:setTopMargin(372.6600)
layout:setBottomMargin(315.3400)
naozhuang_panel:addChild(tip_wait_naozhuang)

--Create tip_wait_tongnao
local tip_wait_tongnao = ccui.ImageView:create()
tip_wait_tongnao:ignoreContentAdaptWithSize(false)
tip_wait_tongnao:loadTexture("app/part/xymj/naozhuang/res/wait_tongnao_tip.png",0)
tip_wait_tongnao:setLayoutComponentEnabled(true)
tip_wait_tongnao:setName("tip_wait_tongnao")
tip_wait_tongnao:setTag(285)
tip_wait_tongnao:setCascadeColorEnabled(true)
tip_wait_tongnao:setCascadeOpacityEnabled(true)
tip_wait_tongnao:setPosition(647.5800, 331.3400)
layout = ccui.LayoutComponent:bindLayoutComponent(tip_wait_tongnao)
layout:setPositionPercentX(0.5059)
layout:setPositionPercentY(0.4602)
layout:setPercentWidth(0.2359)
layout:setPercentHeight(0.0444)
layout:setSize({width = 302.0000, height = 32.0000})
layout:setLeftMargin(496.5800)
layout:setRightMargin(481.4200)
layout:setTopMargin(372.6600)
layout:setBottomMargin(315.3400)
naozhuang_panel:addChild(tip_wait_tongnao)

--Create naozhuang_tip
local naozhuang_tip = ccui.ImageView:create()
naozhuang_tip:ignoreContentAdaptWithSize(false)
naozhuang_tip:loadTexture("app/part/xymj/naozhuang/res/naozhuang_tip.png",0)
naozhuang_tip:setLayoutComponentEnabled(true)
naozhuang_tip:setName("naozhuang_tip")
naozhuang_tip:setTag(286)
naozhuang_tip:setCascadeColorEnabled(true)
naozhuang_tip:setCascadeOpacityEnabled(true)
naozhuang_tip:setPosition(647.5800, 264.3400)
layout = ccui.LayoutComponent:bindLayoutComponent(naozhuang_tip)
layout:setPositionPercentX(0.5059)
layout:setPositionPercentY(0.3671)
layout:setPercentWidth(0.2352)
layout:setPercentHeight(0.0389)
layout:setSize({width = 301.0000, height = 28.0000})
layout:setLeftMargin(497.0800)
layout:setRightMargin(481.9200)
layout:setTopMargin(441.6600)
layout:setBottomMargin(250.3400)
naozhuang_panel:addChild(naozhuang_tip)

--Create btn_nao
local btn_nao = ccui.Button:create()
btn_nao:ignoreContentAdaptWithSize(false)
btn_nao:loadTextureNormal("app/part/xymj/naozhuang/res/btn_bg_orgrange.png",0)
btn_nao:loadTexturePressed("Default/Button_Press.png",0)
btn_nao:loadTextureDisabled("Default/Button_Disable.png",0)
btn_nao:setTitleFontSize(14)
btn_nao:setTitleColor({r = 65, g = 65, b = 70})
btn_nao:setScale9Enabled(true)
btn_nao:setCapInsets({x = 15, y = 11, width = 175, height = 61})
btn_nao:setLayoutComponentEnabled(true)
btn_nao:setName("btn_nao")
btn_nao:setTag(287)
btn_nao:setCascadeColorEnabled(true)
btn_nao:setCascadeOpacityEnabled(true)
btn_nao:setPosition(463.1976, 174.9316)
if callBackProvider~=nil then
      btn_nao:addClickEventListener(callBackProvider("NaozhuangLayer-UI.lua", btn_nao, "onSelectNao"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btn_nao)
layout:setPositionPercentX(0.3619)
layout:setPositionPercentY(0.2430)
layout:setPercentWidth(0.1602)
layout:setPercentHeight(0.1153)
layout:setSize({width = 205.0000, height = 83.0000})
layout:setLeftMargin(360.6976)
layout:setRightMargin(714.3024)
layout:setTopMargin(503.5684)
layout:setBottomMargin(133.4316)
naozhuang_panel:addChild(btn_nao)

--Create image_naozhuang
local image_naozhuang = ccui.ImageView:create()
image_naozhuang:ignoreContentAdaptWithSize(false)
image_naozhuang:loadTexture("app/part/xymj/naozhuang/res/btn_naozhuang_text.png",0)
image_naozhuang:setLayoutComponentEnabled(true)
image_naozhuang:setName("image_naozhuang")
image_naozhuang:setTag(289)
image_naozhuang:setCascadeColorEnabled(true)
image_naozhuang:setCascadeOpacityEnabled(true)
image_naozhuang:setPosition(102.5000, 41.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(image_naozhuang)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.4537)
layout:setPercentHeight(0.5181)
layout:setSize({width = 93.0000, height = 43.0000})
layout:setLeftMargin(56.0000)
layout:setRightMargin(56.0000)
layout:setTopMargin(20.0000)
layout:setBottomMargin(20.0000)
btn_nao:addChild(image_naozhuang)

--Create image_tongnao
local image_tongnao = ccui.ImageView:create()
image_tongnao:ignoreContentAdaptWithSize(false)
image_tongnao:loadTexture("app/part/xymj/naozhuang/res/btn_tongnao_text.png",0)
image_tongnao:setLayoutComponentEnabled(true)
image_tongnao:setName("image_tongnao")
image_tongnao:setTag(290)
image_tongnao:setCascadeColorEnabled(true)
image_tongnao:setCascadeOpacityEnabled(true)
image_tongnao:setPosition(102.5000, 41.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(image_tongnao)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.4537)
layout:setPercentHeight(0.5181)
layout:setSize({width = 93.0000, height = 43.0000})
layout:setLeftMargin(56.0000)
layout:setRightMargin(56.0000)
layout:setTopMargin(20.0000)
layout:setBottomMargin(20.0000)
btn_nao:addChild(image_tongnao)

--Create btn_bunao
local btn_bunao = ccui.Button:create()
btn_bunao:ignoreContentAdaptWithSize(false)
btn_bunao:loadTextureNormal("app/part/xymj/naozhuang/res/btn_bg_green.png",0)
btn_bunao:loadTexturePressed("Default/Button_Press.png",0)
btn_bunao:loadTextureDisabled("Default/Button_Disable.png",0)
btn_bunao:setTitleFontSize(14)
btn_bunao:setTitleColor({r = 65, g = 65, b = 70})
btn_bunao:setScale9Enabled(true)
btn_bunao:setCapInsets({x = 15, y = 11, width = 175, height = 61})
btn_bunao:setLayoutComponentEnabled(true)
btn_bunao:setName("btn_bunao")
btn_bunao:setTag(288)
btn_bunao:setCascadeColorEnabled(true)
btn_bunao:setCascadeOpacityEnabled(true)
btn_bunao:setPosition(815.9700, 174.9300)
if callBackProvider~=nil then
      btn_bunao:addClickEventListener(callBackProvider("NaozhuangLayer-UI.lua", btn_bunao, "onSelectBunao"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btn_bunao)
layout:setPositionPercentX(0.6375)
layout:setPositionPercentY(0.2430)
layout:setPercentWidth(0.1602)
layout:setPercentHeight(0.1153)
layout:setSize({width = 205.0000, height = 83.0000})
layout:setLeftMargin(713.4700)
layout:setRightMargin(361.5300)
layout:setTopMargin(503.5700)
layout:setBottomMargin(133.4300)
naozhuang_panel:addChild(btn_bunao)

--Create image_bunao
local image_bunao = ccui.ImageView:create()
image_bunao:ignoreContentAdaptWithSize(false)
image_bunao:loadTexture("app/part/xymj/naozhuang/res/btn_bunao_text.png",0)
image_bunao:setLayoutComponentEnabled(true)
image_bunao:setName("image_bunao")
image_bunao:setTag(291)
image_bunao:setCascadeColorEnabled(true)
image_bunao:setCascadeOpacityEnabled(true)
image_bunao:setPosition(102.5000, 41.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(image_bunao)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.4585)
layout:setPercentHeight(0.5181)
layout:setSize({width = 94.0000, height = 43.0000})
layout:setLeftMargin(55.5000)
layout:setRightMargin(55.5000)
layout:setTopMargin(20.0000)
layout:setBottomMargin(20.0000)
btn_bunao:addChild(image_bunao)

--Create Node_center
local Node_center=cc.Node:create()
Node_center:setName("Node_center")
Node_center:setTag(4482)
Node_center:setCascadeColorEnabled(true)
Node_center:setCascadeOpacityEnabled(true)
Node_center:setPosition(640.0000, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Node_center)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setVerticalEdge(3)
layout:setLeftMargin(640.0000)
layout:setRightMargin(640.0000)
layout:setTopMargin(360.0000)
layout:setBottomMargin(360.0000)
Layer:addChild(Node_center)

--Create dipan
local dipan = ccui.ImageView:create()
dipan:ignoreContentAdaptWithSize(false)
dipan:loadTexture("app/part/xymj/naozhuang/res/dipan2.png",0)
dipan:setLayoutComponentEnabled(true)
dipan:setName("dipan")
dipan:setTag(4497)
dipan:setCascadeColorEnabled(true)
dipan:setCascadeOpacityEnabled(true)
dipan:setPosition(-2.0006, 67.9978)
layout = ccui.LayoutComponent:bindLayoutComponent(dipan)
layout:setSize({width = 74.0000, height = 52.0000})
layout:setLeftMargin(-39.0006)
layout:setRightMargin(-34.9994)
layout:setTopMargin(-93.9978)
layout:setBottomMargin(41.9978)
Node_center:addChild(dipan)

--Create bearing_time
local bearing_time = ccui.TextAtlas:create([[88]],
													"app/part/xymj/mj3dtable/res/time_num.png",
													30,
													37,
													"0")
bearing_time:setLayoutComponentEnabled(true)
bearing_time:setName("bearing_time")
bearing_time:setTag(4498)
bearing_time:setCascadeColorEnabled(true)
bearing_time:setCascadeOpacityEnabled(true)
bearing_time:setPosition(36.1821, 29.8173)
layout = ccui.LayoutComponent:bindLayoutComponent(bearing_time)
layout:setPositionPercentX(0.4889)
layout:setPositionPercentY(0.5734)
layout:setPercentWidth(0.8108)
layout:setPercentHeight(0.7115)
layout:setSize({width = 60.0000, height = 37.0000})
layout:setLeftMargin(6.1821)
layout:setRightMargin(7.8179)
layout:setTopMargin(3.6827)
layout:setBottomMargin(11.3173)
dipan:addChild(bearing_time)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

