--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create gang_sprite
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjcardopt/res/opt_picture.plist")
local gang_sprite = cc.Sprite:createWithSpriteFrameName("app/part/xymj/mjcardopt/res/gang_ani_1.png")
gang_sprite:setName("gang_sprite")
gang_sprite:setTag(51)
gang_sprite:setCascadeColorEnabled(true)
gang_sprite:setCascadeOpacityEnabled(true)
gang_sprite:setVisible(false)
layout = ccui.LayoutComponent:bindLayoutComponent(gang_sprite)
layout:setSize({width = 200.0000, height = 170.0000})
layout:setLeftMargin(-100.0000)
layout:setRightMargin(-100.0000)
layout:setTopMargin(-85.0000)
layout:setBottomMargin(-85.0000)
gang_sprite:setBlendFunc({src = 1, dst = 771})
Node:addChild(gang_sprite)

--Create peng_sprite
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjcardopt/res/opt_picture.plist")
local peng_sprite = cc.Sprite:createWithSpriteFrameName("app/part/xymj/mjcardopt/res/peng_ani_1.png")
peng_sprite:setName("peng_sprite")
peng_sprite:setTag(52)
peng_sprite:setCascadeColorEnabled(true)
peng_sprite:setCascadeOpacityEnabled(true)
peng_sprite:setVisible(false)
layout = ccui.LayoutComponent:bindLayoutComponent(peng_sprite)
layout:setSize({width = 200.0000, height = 170.0000})
layout:setLeftMargin(-100.0000)
layout:setRightMargin(-100.0000)
layout:setTopMargin(-85.0000)
layout:setBottomMargin(-85.0000)
peng_sprite:setBlendFunc({src = 1, dst = 771})
Node:addChild(peng_sprite)

--Create hu_sprite
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjcardopt/res/opt_picture.plist")
local hu_sprite = cc.Sprite:createWithSpriteFrameName("app/part/xymj/mjcardopt/res/hu_ani_1.png")
hu_sprite:setName("hu_sprite")
hu_sprite:setTag(53)
hu_sprite:setCascadeColorEnabled(true)
hu_sprite:setCascadeOpacityEnabled(true)
hu_sprite:setVisible(false)
layout = ccui.LayoutComponent:bindLayoutComponent(hu_sprite)
layout:setSize({width = 200.0000, height = 170.0000})
layout:setLeftMargin(-100.0000)
layout:setRightMargin(-100.0000)
layout:setTopMargin(-85.0000)
layout:setBottomMargin(-85.0000)
hu_sprite:setBlendFunc({src = 1, dst = 771})
Node:addChild(hu_sprite)

--Create chi_sprite
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjcardopt/res/opt_picture.plist")
local chi_sprite = cc.Sprite:createWithSpriteFrameName("app/part/xymj/mjcardopt/res/chi_ani_1.png")
chi_sprite:setName("chi_sprite")
chi_sprite:setTag(146)
chi_sprite:setCascadeColorEnabled(true)
chi_sprite:setCascadeOpacityEnabled(true)
chi_sprite:setVisible(false)
chi_sprite:setPosition(10.0000, -10.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(chi_sprite)
layout:setSize({width = 200.0000, height = 170.0000})
layout:setLeftMargin(-90.0000)
layout:setRightMargin(-110.0000)
layout:setTopMargin(-75.0000)
layout:setBottomMargin(-95.0000)
chi_sprite:setBlendFunc({src = 1, dst = 771})
Node:addChild(chi_sprite)

--Create qjgang_imageview
local qjgang_imageview = ccui.ImageView:create()
qjgang_imageview:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjcardopt/res/opt_picture.plist")
qjgang_imageview:loadTexture("app/part/xymj/mjcardopt/res/minggang.png",1)
qjgang_imageview:setLayoutComponentEnabled(true)
qjgang_imageview:setName("qjgang_imageview")
qjgang_imageview:setTag(67)
qjgang_imageview:setCascadeColorEnabled(true)
qjgang_imageview:setCascadeOpacityEnabled(true)
qjgang_imageview:setVisible(false)
layout = ccui.LayoutComponent:bindLayoutComponent(qjgang_imageview)
layout:setSize({width = 366.0000, height = 115.0000})
layout:setLeftMargin(-183.0000)
layout:setRightMargin(-183.0000)
layout:setTopMargin(-57.5000)
layout:setBottomMargin(-57.5000)
Node:addChild(qjgang_imageview)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(49)
result['animation']:setTimeSpeed(1.0000)

--Create FileDataTimeline
local FileDataTimeline = ccs.Timeline:create()

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjcardopt/res/opt_picture.plist")
localFrame:setTextureName("app/part/xymj/mjcardopt/res/gang_ani_1.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(7)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjcardopt/res/opt_picture.plist")
localFrame:setTextureName("app/part/xymj/mjcardopt/res/gang_ani_2.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(14)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjcardopt/res/opt_picture.plist")
localFrame:setTextureName("app/part/xymj/mjcardopt/res/gang_ani_3.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(21)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjcardopt/res/opt_picture.plist")
localFrame:setTextureName("app/part/xymj/mjcardopt/res/gang_ani_4.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(28)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjcardopt/res/opt_picture.plist")
localFrame:setTextureName("app/part/xymj/mjcardopt/res/gang_ani_5.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(35)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjcardopt/res/opt_picture.plist")
localFrame:setTextureName("app/part/xymj/mjcardopt/res/gang_ani_6.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(42)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjcardopt/res/opt_picture.plist")
localFrame:setTextureName("app/part/xymj/mjcardopt/res/gang_ani_7.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(49)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjcardopt/res/opt_picture.plist")
localFrame:setTextureName("app/part/xymj/mjcardopt/res/gang_ani_8.png")
FileDataTimeline:addFrame(localFrame)

result['animation']:addTimeline(FileDataTimeline)
FileDataTimeline:setNode(gang_sprite)

--Create FileDataTimeline
local FileDataTimeline = ccs.Timeline:create()

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjcardopt/res/opt_picture.plist")
localFrame:setTextureName("app/part/xymj/mjcardopt/res/peng_ani_1.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(7)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjcardopt/res/opt_picture.plist")
localFrame:setTextureName("app/part/xymj/mjcardopt/res/peng_ani_2.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(14)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjcardopt/res/opt_picture.plist")
localFrame:setTextureName("app/part/xymj/mjcardopt/res/peng_ani_3.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(21)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjcardopt/res/opt_picture.plist")
localFrame:setTextureName("app/part/xymj/mjcardopt/res/peng_ani_4.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(28)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjcardopt/res/opt_picture.plist")
localFrame:setTextureName("app/part/xymj/mjcardopt/res/peng_ani_5.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(35)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjcardopt/res/opt_picture.plist")
localFrame:setTextureName("app/part/xymj/mjcardopt/res/peng_ani_6.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(42)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjcardopt/res/opt_picture.plist")
localFrame:setTextureName("app/part/xymj/mjcardopt/res/peng_ani_7.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(49)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjcardopt/res/opt_picture.plist")
localFrame:setTextureName("app/part/xymj/mjcardopt/res/peng_ani_8.png")
FileDataTimeline:addFrame(localFrame)

result['animation']:addTimeline(FileDataTimeline)
FileDataTimeline:setNode(peng_sprite)

--Create FileDataTimeline
local FileDataTimeline = ccs.Timeline:create()

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjcardopt/res/opt_picture.plist")
localFrame:setTextureName("app/part/xymj/mjcardopt/res/hu_ani_1.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(7)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjcardopt/res/opt_picture.plist")
localFrame:setTextureName("app/part/xymj/mjcardopt/res/hu_ani_2.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(14)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjcardopt/res/opt_picture.plist")
localFrame:setTextureName("app/part/xymj/mjcardopt/res/hu_ani_3.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(21)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjcardopt/res/opt_picture.plist")
localFrame:setTextureName("app/part/xymj/mjcardopt/res/hu_ani_4.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(28)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjcardopt/res/opt_picture.plist")
localFrame:setTextureName("app/part/xymj/mjcardopt/res/hu_ani_5.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(35)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjcardopt/res/opt_picture.plist")
localFrame:setTextureName("app/part/xymj/mjcardopt/res/hu_ani_6.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(42)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjcardopt/res/opt_picture.plist")
localFrame:setTextureName("app/part/xymj/mjcardopt/res/hu_ani_7.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(49)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjcardopt/res/opt_picture.plist")
localFrame:setTextureName("app/part/xymj/mjcardopt/res/hu_ani_8.png")
FileDataTimeline:addFrame(localFrame)

result['animation']:addTimeline(FileDataTimeline)
FileDataTimeline:setNode(hu_sprite)

--Create FileDataTimeline
local FileDataTimeline = ccs.Timeline:create()

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjcardopt/res/opt_picture.plist")
localFrame:setTextureName("app/part/xymj/mjcardopt/res/chi_ani_1.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(7)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjcardopt/res/opt_picture.plist")
localFrame:setTextureName("app/part/xymj/mjcardopt/res/chi_ani_2.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(14)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjcardopt/res/opt_picture.plist")
localFrame:setTextureName("app/part/xymj/mjcardopt/res/chi_ani_3.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(21)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjcardopt/res/opt_picture.plist")
localFrame:setTextureName("app/part/xymj/mjcardopt/res/chi_ani_4.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(28)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjcardopt/res/opt_picture.plist")
localFrame:setTextureName("app/part/xymj/mjcardopt/res/chi_ani_5.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(35)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjcardopt/res/opt_picture.plist")
localFrame:setTextureName("app/part/xymj/mjcardopt/res/chi_ani_6.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(42)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjcardopt/res/opt_picture.plist")
localFrame:setTextureName("app/part/xymj/mjcardopt/res/chi_ani_7.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(49)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjcardopt/res/opt_picture.plist")
localFrame:setTextureName("app/part/xymj/mjcardopt/res/chi_ani_8.png")
FileDataTimeline:addFrame(localFrame)

result['animation']:addTimeline(FileDataTimeline)
FileDataTimeline:setNode(chi_sprite)
--Create Animation List

result['root'] = Node
return result;
end

return Result

