--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create touch_mask
local touch_mask = ccui.Button:create()
touch_mask:ignoreContentAdaptWithSize(false)
touch_mask:loadTextureDisabled("Default/Button_Disable.png",0)
touch_mask:setTitleFontSize(14)
touch_mask:setTitleColor({r = 65, g = 65, b = 70})
touch_mask:setScale9Enabled(true)
touch_mask:setCapInsets({x = -15, y = -4, width = 30, height = 8})
touch_mask:setTouchEnabled(false);
touch_mask:setLayoutComponentEnabled(true)
touch_mask:setName("touch_mask")
touch_mask:setTag(633)
touch_mask:setCascadeColorEnabled(true)
touch_mask:setCascadeOpacityEnabled(true)
touch_mask:setPosition(640.0000, 360.0000)
if callBackProvider~=nil then
      touch_mask:addClickEventListener(callBackProvider("RoomMenuLayer-UI.lua", touch_mask, "MaskClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(touch_mask)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
Layer:addChild(touch_mask)

--Create menu_panel
local menu_panel = ccui.Layout:create()
menu_panel:ignoreContentAdaptWithSize(false)
menu_panel:setBackGroundImage("app/part/xymj/roommenu/res/menu_panel_bg.png",0)
menu_panel:setClippingEnabled(false)
menu_panel:setBackGroundImageCapInsets({x = 107, y = 13, width = 100, height = 14})
menu_panel:setBackGroundColorOpacity(102)
menu_panel:setBackGroundImageScale9Enabled(true)
menu_panel:setTouchEnabled(true);
menu_panel:setLayoutComponentEnabled(true)
menu_panel:setName("menu_panel")
menu_panel:setTag(639)
menu_panel:setCascadeColorEnabled(true)
menu_panel:setCascadeOpacityEnabled(true)
menu_panel:setVisible(false)
menu_panel:setPosition(831.9999, -361.0000)
if callBackProvider~=nil then
      menu_panel:addClickEventListener(callBackProvider("RoomMenuLayer-UI.lua", menu_panel, "menu_panel_click"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(menu_panel)
layout:setPositionPercentX(0.6500)
layout:setPositionPercentY(-0.5014)
layout:setPercentWidth(0.3500)
layout:setPercentHeight(1.5014)
layout:setSize({width = 448.0000, height = 1081.0000})
layout:setHorizontalEdge(2)
layout:setVerticalEdge(2)
layout:setLeftMargin(831.9999)
layout:setRightMargin(0.0001)
layout:setBottomMargin(-361.0000)
Layer:addChild(menu_panel)

--Create close_menu_btn
local close_menu_btn = ccui.Button:create()
close_menu_btn:ignoreContentAdaptWithSize(false)
close_menu_btn:loadTextureNormal("app/part/xymj/roommenu/res/menu_up.png",0)
close_menu_btn:loadTexturePressed("app/part/xymj/roommenu/res/menu_up_light.png",0)
close_menu_btn:setTitleFontSize(14)
close_menu_btn:setTitleColor({r = 65, g = 65, b = 70})
close_menu_btn:setScale9Enabled(true)
close_menu_btn:setCapInsets({x = 15, y = 11, width = 36, height = 44})
close_menu_btn:setLayoutComponentEnabled(true)
close_menu_btn:setName("close_menu_btn")
close_menu_btn:setTag(640)
close_menu_btn:setCascadeColorEnabled(true)
close_menu_btn:setCascadeOpacityEnabled(true)
close_menu_btn:setPosition(405.0000, 1041.0000)
if callBackProvider~=nil then
      close_menu_btn:addClickEventListener(callBackProvider("RoomMenuLayer-UI.lua", close_menu_btn, "CollapseClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(close_menu_btn)
layout:setPositionPercentX(0.9040)
layout:setPositionPercentY(0.9630)
layout:setPercentWidth(0.1473)
layout:setPercentHeight(0.0611)
layout:setSize({width = 66.0000, height = 66.0000})
layout:setHorizontalEdge(2)
layout:setVerticalEdge(2)
layout:setLeftMargin(372.0000)
layout:setRightMargin(10.0000)
layout:setTopMargin(7.0000)
layout:setBottomMargin(1008.0000)
menu_panel:addChild(close_menu_btn)

--Create close_room_btn
local close_room_btn = ccui.Button:create()
close_room_btn:ignoreContentAdaptWithSize(false)
close_room_btn:loadTextureNormal("app/part/xymj/roommenu/res/jiesan_fangjian.png",0)
close_room_btn:loadTexturePressed("app/part/xymj/roommenu/res/jiesan_fangjian_l.png",0)
close_room_btn:loadTextureDisabled("Default/Button_Disable.png",0)
close_room_btn:setTitleFontSize(14)
close_room_btn:setTitleColor({r = 65, g = 65, b = 70})
close_room_btn:setScale9Enabled(true)
close_room_btn:setCapInsets({x = 15, y = 11, width = 36, height = 64})
close_room_btn:setLayoutComponentEnabled(true)
close_room_btn:setName("close_room_btn")
close_room_btn:setTag(641)
close_room_btn:setCascadeColorEnabled(true)
close_room_btn:setCascadeOpacityEnabled(true)
close_room_btn:setPosition(405.0000, 732.3000)
if callBackProvider~=nil then
      close_room_btn:addClickEventListener(callBackProvider("RoomMenuLayer-UI.lua", close_room_btn, "CloseRoomClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(close_room_btn)
layout:setPositionPercentX(0.9040)
layout:setPositionPercentY(0.6774)
layout:setPercentWidth(0.1473)
layout:setPercentHeight(0.0796)
layout:setSize({width = 66.0000, height = 86.0000})
layout:setHorizontalEdge(2)
layout:setVerticalEdge(2)
layout:setLeftMargin(372.0000)
layout:setRightMargin(10.0000)
layout:setTopMargin(305.7000)
layout:setBottomMargin(689.3000)
menu_panel:addChild(close_room_btn)

--Create leave_room_btn
local leave_room_btn = ccui.Button:create()
leave_room_btn:ignoreContentAdaptWithSize(false)
leave_room_btn:loadTextureNormal("app/part/xymj/roommenu/res/exit_room_btn.png",0)
leave_room_btn:loadTexturePressed("app/part/xymj/roommenu/res/exit_room_btn_light.png",0)
leave_room_btn:loadTextureDisabled("Default/Button_Disable.png",0)
leave_room_btn:setTitleFontSize(14)
leave_room_btn:setTitleColor({r = 65, g = 65, b = 70})
leave_room_btn:setScale9Enabled(true)
leave_room_btn:setCapInsets({x = 15, y = 11, width = 36, height = 63})
leave_room_btn:setLayoutComponentEnabled(true)
leave_room_btn:setName("leave_room_btn")
leave_room_btn:setTag(11)
leave_room_btn:setCascadeColorEnabled(true)
leave_room_btn:setCascadeOpacityEnabled(true)
leave_room_btn:setPosition(405.0000, 732.6217)
if callBackProvider~=nil then
      leave_room_btn:addClickEventListener(callBackProvider("RoomMenuLayer-UI.lua", leave_room_btn, "LeaveRoomClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(leave_room_btn)
layout:setPositionPercentX(0.9040)
layout:setPositionPercentY(0.6777)
layout:setPercentWidth(0.1473)
layout:setPercentHeight(0.0786)
layout:setSize({width = 66.0000, height = 85.0000})
layout:setHorizontalEdge(2)
layout:setVerticalEdge(2)
layout:setLeftMargin(372.0000)
layout:setRightMargin(10.0000)
layout:setTopMargin(305.8783)
layout:setBottomMargin(690.1217)
menu_panel:addChild(leave_room_btn)

--Create rules_btn
local rules_btn = ccui.Button:create()
rules_btn:ignoreContentAdaptWithSize(false)
rules_btn:loadTextureNormal("app/part/xymj/roommenu/res/rules_btn.png",0)
rules_btn:loadTexturePressed("app/part/xymj/roommenu/res/rules_btn_light.png",0)
rules_btn:setTitleFontSize(14)
rules_btn:setTitleColor({r = 65, g = 65, b = 70})
rules_btn:setScale9Enabled(true)
rules_btn:setCapInsets({x = 15, y = 11, width = 36, height = 64})
rules_btn:setLayoutComponentEnabled(true)
rules_btn:setName("rules_btn")
rules_btn:setTag(643)
rules_btn:setCascadeColorEnabled(true)
rules_btn:setCascadeOpacityEnabled(true)
rules_btn:setPosition(404.9996, 638.3210)
if callBackProvider~=nil then
      rules_btn:addClickEventListener(callBackProvider("RoomMenuLayer-UI.lua", rules_btn, "RulesClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(rules_btn)
layout:setPositionPercentX(0.9040)
layout:setPositionPercentY(0.5905)
layout:setPercentWidth(0.1473)
layout:setPercentHeight(0.0796)
layout:setSize({width = 66.0000, height = 86.0000})
layout:setHorizontalEdge(2)
layout:setVerticalEdge(2)
layout:setLeftMargin(371.9996)
layout:setRightMargin(10.0004)
layout:setTopMargin(399.6790)
layout:setBottomMargin(595.3210)
menu_panel:addChild(rules_btn)

--Create gps_btn
local gps_btn = ccui.Button:create()
gps_btn:ignoreContentAdaptWithSize(false)
gps_btn:loadTextureNormal("app/part/xymj/roommenu/res/gps_btn.png",0)
gps_btn:loadTexturePressed("app/part/xymj/roommenu/res/gps_btn_light.png",0)
gps_btn:setTitleFontSize(14)
gps_btn:setTitleColor({r = 65, g = 65, b = 70})
gps_btn:setScale9Enabled(true)
gps_btn:setCapInsets({x = 15, y = 11, width = 36, height = 64})
gps_btn:setLayoutComponentEnabled(true)
gps_btn:setName("gps_btn")
gps_btn:setTag(644)
gps_btn:setCascadeColorEnabled(true)
gps_btn:setCascadeOpacityEnabled(true)
gps_btn:setPosition(404.9997, 940.0000)
if callBackProvider~=nil then
      gps_btn:addTouchEventListener(callBackProvider("RoomMenuLayer-UI.lua", gps_btn, "GpsClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(gps_btn)
layout:setPositionPercentX(0.9040)
layout:setPositionPercentY(0.8696)
layout:setPercentWidth(0.1473)
layout:setPercentHeight(0.0796)
layout:setSize({width = 66.0000, height = 86.0000})
layout:setHorizontalEdge(2)
layout:setVerticalEdge(2)
layout:setLeftMargin(371.9997)
layout:setRightMargin(10.0003)
layout:setTopMargin(98.0000)
layout:setBottomMargin(897.0000)
menu_panel:addChild(gps_btn)

--Create liushui_btn
local liushui_btn = ccui.Button:create()
liushui_btn:ignoreContentAdaptWithSize(false)
liushui_btn:loadTextureNormal("app/part/xymj/roommenu/res/liushui.png",0)
liushui_btn:loadTexturePressed("app/part/xymj/roommenu/res/liushui_light.png",0)
liushui_btn:setTitleFontSize(14)
liushui_btn:setTitleColor({r = 65, g = 65, b = 70})
liushui_btn:setScale9Enabled(true)
liushui_btn:setCapInsets({x = 15, y = 11, width = 36, height = 64})
liushui_btn:setLayoutComponentEnabled(true)
liushui_btn:setName("liushui_btn")
liushui_btn:setTag(1406)
liushui_btn:setCascadeColorEnabled(true)
liushui_btn:setCascadeOpacityEnabled(true)
liushui_btn:setVisible(false)
liushui_btn:setPosition(405.0000, 628.6300)
layout = ccui.LayoutComponent:bindLayoutComponent(liushui_btn)
layout:setPositionPercentX(0.9040)
layout:setPositionPercentY(0.5815)
layout:setPercentWidth(0.1473)
layout:setPercentHeight(0.0796)
layout:setSize({width = 66.0000, height = 86.0000})
layout:setHorizontalEdge(2)
layout:setVerticalEdge(2)
layout:setLeftMargin(372.0000)
layout:setRightMargin(10.0000)
layout:setTopMargin(409.3700)
layout:setBottomMargin(585.6300)
menu_panel:addChild(liushui_btn)

--Create setting_btn
local setting_btn = ccui.Button:create()
setting_btn:ignoreContentAdaptWithSize(false)
setting_btn:loadTextureNormal("app/part/xymj/roommenu/res/aj_setting.png",0)
setting_btn:loadTexturePressed("app/part/xymj/roommenu/res/aj_setting_light.png",0)
setting_btn:loadTextureDisabled("Default/Button_Disable.png",0)
setting_btn:setTitleFontSize(14)
setting_btn:setTitleColor({r = 65, g = 65, b = 70})
setting_btn:setScale9Enabled(true)
setting_btn:setCapInsets({x = 15, y = 11, width = 36, height = 62})
setting_btn:setLayoutComponentEnabled(true)
setting_btn:setName("setting_btn")
setting_btn:setTag(1432)
setting_btn:setCascadeColorEnabled(true)
setting_btn:setCascadeOpacityEnabled(true)
setting_btn:setPosition(405.0003, 836.2700)
if callBackProvider~=nil then
      setting_btn:addClickEventListener(callBackProvider("RoomMenuLayer-UI.lua", setting_btn, "SettingsClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(setting_btn)
layout:setPositionPercentX(0.9040)
layout:setPositionPercentY(0.7736)
layout:setPercentWidth(0.1473)
layout:setPercentHeight(0.0777)
layout:setSize({width = 66.0000, height = 84.0000})
layout:setHorizontalEdge(2)
layout:setVerticalEdge(2)
layout:setLeftMargin(372.0003)
layout:setRightMargin(9.9997)
layout:setTopMargin(202.7300)
layout:setBottomMargin(794.2700)
menu_panel:addChild(setting_btn)

--Create menu_ctl
local menu_ctl = ccui.Button:create()
menu_ctl:ignoreContentAdaptWithSize(false)
menu_ctl:loadTextureNormal("app/part/xymj/roommenu/res/menu_down.png",0)
menu_ctl:loadTexturePressed("app/part/xymj/roommenu/res/menu_down_light.png",0)
menu_ctl:setTitleFontSize(14)
menu_ctl:setTitleColor({r = 65, g = 65, b = 70})
menu_ctl:setScale9Enabled(true)
menu_ctl:setCapInsets({x = 15, y = 11, width = 36, height = 44})
menu_ctl:setLayoutComponentEnabled(true)
menu_ctl:setName("menu_ctl")
menu_ctl:setTag(1348)
menu_ctl:setCascadeColorEnabled(true)
menu_ctl:setCascadeOpacityEnabled(true)
menu_ctl:setPosition(1237.0000, 680.0000)
if callBackProvider~=nil then
      menu_ctl:addClickEventListener(callBackProvider("RoomMenuLayer-UI.lua", menu_ctl, "menuShowList"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(menu_ctl)
layout:setPositionPercentX(0.9664)
layout:setPositionPercentY(0.9444)
layout:setPercentWidth(0.0516)
layout:setPercentHeight(0.0917)
layout:setSize({width = 66.0000, height = 66.0000})
layout:setHorizontalEdge(2)
layout:setVerticalEdge(2)
layout:setLeftMargin(1204.0000)
layout:setRightMargin(10.0000)
layout:setTopMargin(7.0000)
layout:setBottomMargin(647.0000)
Layer:addChild(menu_ctl)

--Create leave_room_coin_btn
local leave_room_coin_btn = ccui.Button:create()
leave_room_coin_btn:ignoreContentAdaptWithSize(false)
leave_room_coin_btn:loadTextureNormal("app/part/xymj/roommenu/res/exit_room_btn.png",0)
leave_room_coin_btn:loadTexturePressed("app/part/xymj/roommenu/res/exit_room_btn_light.png",0)
leave_room_coin_btn:loadTextureDisabled("Default/Button_Disable.png",0)
leave_room_coin_btn:setTitleFontSize(14)
leave_room_coin_btn:setTitleColor({r = 65, g = 65, b = 70})
leave_room_coin_btn:setScale9Enabled(true)
leave_room_coin_btn:setCapInsets({x = 15, y = 11, width = 36, height = 63})
leave_room_coin_btn:setLayoutComponentEnabled(true)
leave_room_coin_btn:setName("leave_room_coin_btn")
leave_room_coin_btn:setTag(7794)
leave_room_coin_btn:setCascadeColorEnabled(true)
leave_room_coin_btn:setCascadeOpacityEnabled(true)
leave_room_coin_btn:setVisible(false)
leave_room_coin_btn:setPosition(40.0001, 625.5992)
if callBackProvider~=nil then
      leave_room_coin_btn:addClickEventListener(callBackProvider("RoomMenuLayer-UI.lua", leave_room_coin_btn, "LeaveRoomClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(leave_room_coin_btn)
layout:setPositionPercentX(0.0313)
layout:setPositionPercentY(0.8689)
layout:setPercentWidth(0.0516)
layout:setPercentHeight(0.1181)
layout:setSize({width = 66.0000, height = 85.0000})
layout:setHorizontalEdge(1)
layout:setVerticalEdge(2)
layout:setLeftMargin(7.0001)
layout:setRightMargin(1207.0000)
layout:setTopMargin(51.9008)
layout:setBottomMargin(583.0992)
Layer:addChild(leave_room_coin_btn)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

