-- This file is generated by x-studio365
-- This file is generated by x-studio365
--[[
*名称:RedpacketMgrLayer
*描述:红包管理界面
*版权:Copyright © 2016-2018 深圳市三只小熊科技有限公司 版权所有
*作者:Hunter.lei
*创建日期:2017.5.2
*修改日期:2017.5.2
*备注:该类属于baseClsss请勿修改，如需修改请详询管理员
]]

local RedpacketMgrLayer = class("RedpacketMgrLayer",cc.load("mvc").ViewBase)
--[[
	界面处理需要保证就算是错误数据也做到不崩溃
	在获取到数据的时候进行checkData操作
]]
RedpacketMgrLayer.Status = {
    STATUS_RED_PACKET_INIT = 0x000000, --初始化状态
    STATUS_RED_PACKET_ = 0x000001, --待领取状态
    STATUS_RED_PACKET_INIT = 0x000002,  --领取状态
}

local CURRENT_MODULE_NAME = ...
function RedpacketMgrLayer:onCreate()
	-- body
    self:addMask()
	self:initWithFilePath("RedpacketMgrLayer",CURRENT_MODULE_NAME)
    self.node.ListView_redpacket:setItemModel(self.node.player_panel2)
    self.node.ListView_redpacket:addScrollViewEventListener(handler(self,RedpacketMgrLayer.onScrollMove))
    self.node.ListView_redpacket:setScrollBarEnabled(false)
    self.node.Slider_bar:addEventListener(handler(self,RedpacketMgrLayer.onSliderDrag))
    local scale = display.width/1280
    self.node.Panel_main:setScale(scale)
    --初始化lisiview的滚动条
    local listInnerSize = self.node.ListView_redpacket:getInnerContainerSize()
    local itemlist = self.node.ListView_redpacket:getItems()
    local size = self.node.ListView_redpacket:getContentSize()
    local d = self.node.ListView_redpacket:getContentSize().height - listInnerSize.height
    local po = self.node.ListView_redpacket:getInnerContainerPosition()        
    local p = po.y / d
    if d == 0 or #itemlist==0 or listInnerSize.height >= 100000000 then
        self.node.Slider_bar:setEnabled(false)
        self.node.Slider_bar:setVisible(false)
    end
    self.node.Text_activity:setString("您还没有红包领取")
    --local data = {"1","2","3","4","5","6","7","8"}
    --self:redpacketDataInfo(data)
end

--滑动条滑动，list跟着刷新位置
function RedpacketMgrLayer:onSliderDrag(ref,event)
    if event == 0 then --位置变化ON_PERCENTAGE_CHANGED = 0
       local percent = ref:getPercent()
       self.node.ListView_redpacket:jumpToPercentVertical(percent)
    end
end


function RedpacketMgrLayer:onScrollMove(ref,event)
    -- body
    print("this is item click:",ref,event)
    if event == ccui.ScrollviewEventType.scrolling then --移动
        --local cur_index = self.node.ListView_redpacket:getCurSelectedIndex()
        local listInnerSize = ref:getInnerContainerSize()
        local size = ref:getContentSize()
        local d = ref:getContentSize().height - listInnerSize.height
        local po = ref:getInnerContainerPosition()
        
        local p = po.y / d
        self.node.Slider_bar:setPercent((1-p)*100)
        --[[elseif event == ccui.ScrollviewEventType.containerMoved then
            local d = 1
            local d2 = 2]]
    end
end

function RedpacketMgrLayer:onClickButton(ref)
    --点击红包上的按钮，拆开红包（发送拆包请求）
    --获取红包id，然后list中找
    --根据状态刷新按钮功能(未拆包，未分享，未领取，已领取)
    self.part:onSplitRedPacket()
end

function RedpacketMgrLayer:onClickClose()
    self:onClose()
end

function RedpacketMgrLayer:updateActivityTime(actSTime,actETime,actDSTime,actDETime)
    local content = "本次活动开放日期：" .. actSTime .. "至" .. actETime .. "            " .. "活动时间:" .. actDSTime .. "至" .. actDETime
    self.node.Text_activity:setString(content)
end
--刷新内容
function RedpacketMgrLayer:redpacketDataInfo(data,order)
    self.node.ListView_redpacket:removeAllChildren()
    local i = 1
    if data ~= nil and order ~= nil then
        for k,v in pairs(order) do
            --if i < 6 then  --最多显示6个
            local item = self.node.Panel_item:clone()
            item.id = data[v].packetId
            self.node.ListView_redpacket:insertCustomItem(item,i-1)
            item  = self.node.ListView_redpacket:getItem(i-1)
            local crTime_text = item:getChildByName("Text_rpTime") --红包生成时间
            local rpContext_text = item:getChildByName("Text_rpTitle") --奖励内容
            local rpValue_text = item:getChildByName("Text_rpValue") --奖励数量
            crTime_text:setString(data[v].createTime)
            rpContext_text:setString(data[v].redPacketName)
            rpValue_text:setString(data[v].redRedPacketNumContent)
            
            local btn_opt = item:getChildByName("Button_opt")
            local img_des = btn_opt:getChildByName("Image_des")    --按钮状态显示图片
            btn_opt.id = data[v].packetId --红包id
            btn_opt.ntype = data[v].prizeType -- 红包类型
            if data[v].packetStatus == 0 then
                --未拆的包
                img_des:loadTexture(self.res_base .. "/split.png",1)
                local s_size = img_des:getVirtualRendererSize()
                img_des:setContentSize(s_size.width,s_size.height)
                btn_opt:addClickEventListener(function(sender)
                    self.part:onSplitRedPacket(sender.id)
                end)
            elseif data[v].packetStatus == 1 then
                --待领取，显示领取按钮
                img_des:loadTexture(self.res_base .. "/icon_rec.png",1)
                local s_size = img_des:getVirtualRendererSize()
                img_des:setContentSize(s_size.width,s_size.height)
                btn_opt:addClickEventListener(function(sender)
                    local name = self.res_base .. "/spine/jinbi_huode"
                    if sender.ntype == 1 then
                        --钻石
                        name = self.res_base .. "/spine/zuanshi_huode"
                    end
                    local spineAni = Util.createSpineAnimation(name,"1",false,ture)
                    spineAni:setPosition(sender:getContentSize().width*0.5,sender:getContentSize().height*0.5)
                    sender:addChild(spineAni)
                    self.part:onReceiveRedPacket(sender.id)
                end)
            elseif data[v].packetStatus == 2 then
                --已经领取则显示已领取，按钮不可以点击
                img_des:setVisible(false)
                btn_opt:setBright(false)
                btn_opt:setTouchEnabled(false);
            elseif data[v].packetStatus == 3 then
                --待分享
                img_des:loadTexture(self.res_base .. "/share.png",1)
                local s_size = img_des:getVirtualRendererSize()
                img_des:setContentSize(s_size.width,s_size.height)
                btn_opt:addClickEventListener(function(sender) 
                    self.part:shareToWX(sender.id)
                end)
            else
                --默认容错处理
                img_des:setVisible(false)
                btn_opt:setBright(false)
                btn_opt:setTouchEnabled(false);
                btn_opt:addClickEventListener(function(sender) 
                end)
            end
            i = i + 1
            --end
        end
        --更新红包数据
        --self.node.Text_descript:setString("")   --设置红包标题
        --seff.node.Text_context:setString("")    --设置红包活动内容（时间）
    end
   local listInnerSize = self.node.ListView_redpacket:getInnerContainerSize()
   local itemlist = self.node.ListView_redpacket:getItems()
   local size = self.node.ListView_redpacket:getContentSize()
   local d = self.node.ListView_redpacket:getContentSize().height - listInnerSize.height
   local po = self.node.ListView_redpacket:getInnerContainerPosition()        
   local p = po.y / d
   if d == 0 or #itemlist==0 or listInnerSize.height >= 100000000 then
     self.node.Slider_bar:setEnabled(false)
     self.node.Slider_bar:setVisible(false)
   end
end

--根据id获取到list的item
function RedpacketMgrLayer:getItemByID(id)
    local item = null
    local itemArray = self.node.ListView_redpacket:getItems()
    for k,v in pairs(itemArray) do
        if id == v.id then
            item = v
            break
        end
    end
    return item
end

--朋友圈分享
function RedpacketMgrLayer:shareToWXCircleFriend(title,content,url)
    self:onClose()
    local bridge = global:getModuleWithId(ModuleDef.BRIDGE_MOD)
    bridge:shareRedPacketToWxCirleOfFriend(title,content,url,"rplogo")
end
--刷新状态
function RedpacketMgrLayer:updateItem(item,status,des)
    --local crTime_text = item:getChildByName("Text_rpTime") --红包生成时间
    --local rpContext_text = item:getChildByName("Text_rpTitle") --奖励内容
    local rpValue_text = item:getChildByName("Text_rpValue") --奖励数量
    if des ~= nil then
        rpValue_text:setString(des)
    end
    --crTime_text:setString(v.createTime)
    --rpContext_text:setString(v.redPacketName)

    
    local btn_opt = item:getChildByName("Button_opt")
    local img_des = btn_opt:getChildByName("Image_des")    --按钮状态显示图片
    btn_opt.id = item.id --红包id
    if status == 0 then
        --未拆的包
        img_des:loadTexture(self.res_base .. "/share.png",1)
        btn_opt:addClickEventListener(function(sender)
            self.part:onSplitRedPacket(sender.id)
        end)
    elseif status == 1 then
        --待领取，显示领取按钮
        img_des:loadTexture(self.res_base .. "/icon_rec.png",1)
        btn_opt:addClickEventListener(function(sender) 
            self.part:onReceiveRedPacket(sender.id)
        end)
    elseif status == 2 then
        --已经领取则显示已领取，按钮不可以点击
        img_des:setVisible(false)
        btn_opt:setBright(false)
        btn_opt:setTouchEnabled(false);
    elseif status == 3 then
        --待分享
        img_des:loadTexture(self.res_base .. "/share.png",1)
        btn_opt:addClickEventListener(function(sender) 
            self.part:shareToWX(sender.id)
        end)
    else
        --默认容错处理
        img_des:setVisible(false)
        btn_opt:setBright(false)
        btn_opt:setTouchEnabled(false);
        btn_opt:addClickEventListener(function(sender) 
        end)
    end
end

function RedpacketMgrLayer:onEnter()
    self.part:onQueryRedPacketReqMsg()
end
--按钮点击
function RedpacketMgrLayer:onClickButton()
    
end

--关闭红包界面
function RedpacketMgrLayer:onClose()
    self.part:onClose()
end


return RedpacketMgrLayer