-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
cc.exports.card_info_pb = {}
module('card_info_pb')


local CARDINFO = protobuf.Descriptor();
local CARDINFO_CARDVALUE_FIELD = protobuf.FieldDescriptor();

CARDINFO_CARDVALUE_FIELD.name = "cardvalue"
CARDINFO_CARDVALUE_FIELD.full_name = ".CardInfo.cardvalue"
CARDINFO_CARDVALUE_FIELD.number = 1
CARDINFO_CARDVALUE_FIELD.index = 0
CARDINFO_CARDVALUE_FIELD.label = 3
CARDINFO_CARDVALUE_FIELD.has_default_value = false
CARDINFO_CARDVALUE_FIELD.default_value = {}
CARDINFO_CARDVALUE_FIELD.type = 13
CARDINFO_CARDVALUE_FIELD.cpp_type = 3

CARDINFO.name = "CardInfo"
CARDINFO.full_name = ".CardInfo"
CARDINFO.nested_types = {}
CARDINFO.enum_types = {}
CARDINFO.fields = {CARDINFO_CARDVALUE_FIELD}
CARDINFO.is_extendable = false
CARDINFO.extensions = {}

CardInfo = protobuf.Message(CARDINFO)

