-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
cc.exports.cptNotify_pb = {}
module('cptNotify_pb')


local COMMNOTIFY = protobuf.Descriptor();
local COMMNOTIFY_RESULT_FIELD = protobuf.FieldDescriptor();
local COMMNOTIFY_RESULTMSG_FIELD = protobuf.FieldDescriptor();
local COMMNOTIFY_TIPS_FIELD = protobuf.FieldDescriptor();

COMMNOTIFY_RESULT_FIELD.name = "result"
COMMNOTIFY_RESULT_FIELD.full_name = ".commNotify.result"
COMMNOTIFY_RESULT_FIELD.number = 1
COMMNOTIFY_RESULT_FIELD.index = 0
COMMNOTIFY_RESULT_FIELD.label = 2
COMMNOTIFY_RESULT_FIELD.has_default_value = false
COMMNOTIFY_RESULT_FIELD.default_value = 0
COMMNOTIFY_RESULT_FIELD.type = 5
COMMNOTIFY_RESULT_FIELD.cpp_type = 1

COMMNOTIFY_RESULTMSG_FIELD.name = "resultMsg"
COMMNOTIFY_RESULTMSG_FIELD.full_name = ".commNotify.resultMsg"
COMMNOTIFY_RESULTMSG_FIELD.number = 2
COMMNOTIFY_RESULTMSG_FIELD.index = 1
COMMNOTIFY_RESULTMSG_FIELD.label = 1
COMMNOTIFY_RESULTMSG_FIELD.has_default_value = false
COMMNOTIFY_RESULTMSG_FIELD.default_value = ""
COMMNOTIFY_RESULTMSG_FIELD.type = 9
COMMNOTIFY_RESULTMSG_FIELD.cpp_type = 9

COMMNOTIFY_TIPS_FIELD.name = "tips"
COMMNOTIFY_TIPS_FIELD.full_name = ".commNotify.tips"
COMMNOTIFY_TIPS_FIELD.number = 3
COMMNOTIFY_TIPS_FIELD.index = 2
COMMNOTIFY_TIPS_FIELD.label = 1
COMMNOTIFY_TIPS_FIELD.has_default_value = false
COMMNOTIFY_TIPS_FIELD.default_value = ""
COMMNOTIFY_TIPS_FIELD.type = 9
COMMNOTIFY_TIPS_FIELD.cpp_type = 9

COMMNOTIFY.name = "commNotify"
COMMNOTIFY.full_name = ".commNotify"
COMMNOTIFY.nested_types = {}
COMMNOTIFY.enum_types = {}
COMMNOTIFY.fields = {COMMNOTIFY_RESULT_FIELD, COMMNOTIFY_RESULTMSG_FIELD, COMMNOTIFY_TIPS_FIELD}
COMMNOTIFY.is_extendable = true
COMMNOTIFY.extensions = {}

commNotify = protobuf.Message(COMMNOTIFY)

