--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create bg
local bg = ccui.ImageView:create()
bg:ignoreContentAdaptWithSize(false)
bg:loadTexture("app/part/xymj/login/res/login_bg.jpg",0)
bg:setTouchEnabled(true);
bg:setLayoutComponentEnabled(true)
bg:setName("bg")
bg:setTag(332)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setPosition(640.0000, 360.0000)
if callBackProvider~=nil then
      bg:addClickEventListener(callBackProvider("UpdateScene-UI.lua", bg, "ClickUpdateInfo"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
Scene:addChild(bg)

--Create loading
local loading = ccui.ImageView:create()
loading:ignoreContentAdaptWithSize(false)
loading:loadTexture("app/part/xymj/login/res/loading.png",0)
loading:setLayoutComponentEnabled(true)
loading:setName("loading")
loading:setTag(433)
loading:setCascadeColorEnabled(true)
loading:setCascadeOpacityEnabled(true)
loading:setVisible(false)
loading:setPosition(640.0000, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(loading)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3922)
layout:setPercentHeight(0.4875)
layout:setSize({width = 502.0000, height = 351.0000})
layout:setLeftMargin(389.0000)
layout:setRightMargin(389.0000)
layout:setTopMargin(184.5000)
layout:setBottomMargin(184.5000)
bg:addChild(loading)

--Create update_progress
local update_progress = ccui.LoadingBar:create()
update_progress:loadTexture("app/part/xymj/login/res/update_progress.png",0)
update_progress:ignoreContentAdaptWithSize(false)
update_progress:setPercent(0)
update_progress:setLayoutComponentEnabled(true)
update_progress:setName("update_progress")
update_progress:setTag(334)
update_progress:setCascadeColorEnabled(true)
update_progress:setCascadeOpacityEnabled(true)
update_progress:setPosition(640.0000, 158.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(update_progress)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.2194)
layout:setPercentWidth(0.6250)
layout:setPercentHeight(0.0361)
layout:setSize({width = 800.0000, height = 26.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(1)
layout:setLeftMargin(240.0000)
layout:setRightMargin(240.0000)
layout:setTopMargin(549.0000)
layout:setBottomMargin(145.0000)
Scene:addChild(update_progress)

--Create update_progress_bg
local update_progress_bg = ccui.ImageView:create()
update_progress_bg:ignoreContentAdaptWithSize(false)
update_progress_bg:loadTexture("app/part/xymj/login/res/update_progress_bg.png",0)
update_progress_bg:setScale9Enabled(true)
update_progress_bg:setCapInsets({x = -158, y = 10, width = 398, height = 6})
update_progress_bg:setLayoutComponentEnabled(true)
update_progress_bg:setName("update_progress_bg")
update_progress_bg:setTag(333)
update_progress_bg:setCascadeColorEnabled(true)
update_progress_bg:setCascadeOpacityEnabled(true)
update_progress_bg:setPosition(395.0000, 14.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(update_progress_bg)
layout:setPositionPercentX(0.4938)
layout:setPositionPercentY(0.5385)
layout:setPercentWidth(0.7825)
layout:setPercentHeight(1.0000)
layout:setSize({width = 626.0000, height = 26.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(1)
layout:setLeftMargin(82.0000)
layout:setRightMargin(92.0000)
layout:setTopMargin(-1.0000)
layout:setBottomMargin(1.0000)
update_progress:addChild(update_progress_bg)

--Create Panel_2
local Panel_2 = ccui.Layout:create()
Panel_2:ignoreContentAdaptWithSize(false)
Panel_2:setClippingEnabled(false)
Panel_2:setBackGroundColorType(1)
Panel_2:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_2:setBackGroundColorOpacity(133)
Panel_2:setTouchEnabled(true);
Panel_2:setLayoutComponentEnabled(true)
Panel_2:setName("Panel_2")
Panel_2:setTag(77)
Panel_2:setCascadeColorEnabled(true)
Panel_2:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_2)
layout:setPercentWidthEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.0694)
layout:setSize({width = 1280.0000, height = 50.0000})
layout:setTopMargin(670.0000)
Scene:addChild(Panel_2)

--Create update_info
local update_info = ccui.Text:create()
update_info:ignoreContentAdaptWithSize(true)
update_info:setTextAreaSize({width = 0, height = 0})
update_info:setFontSize(36)
update_info:setString([[正在检测更新]])
update_info:setTextHorizontalAlignment(1)
update_info:setTextVerticalAlignment(1)
update_info:setTouchEnabled(true);
update_info:setLayoutComponentEnabled(true)
update_info:setName("update_info")
update_info:setTag(335)
update_info:setCascadeColorEnabled(true)
update_info:setCascadeOpacityEnabled(true)
update_info:setPosition(640.0000, 28.9125)
layout = ccui.LayoutComponent:bindLayoutComponent(update_info)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.0402)
layout:setPercentWidth(0.1688)
layout:setPercentHeight(0.0583)
layout:setSize({width = 216.0000, height = 42.0000})
layout:setVerticalEdge(1)
layout:setLeftMargin(532.0000)
layout:setRightMargin(532.0000)
layout:setTopMargin(670.0875)
layout:setBottomMargin(7.9125)
Scene:addChild(update_info)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

