-- This file is generated by x-studio365
--[[
*名称:RedpacketTipsLayer
*描述:红包获得tips界面
*版权:Copyright © 2016-2018 深圳市三只小熊科技有限公司 版权所有
*作者:Hunter.lei
*创建日期:2017.5.2
*修改日期:2017.5.2
*备注:该类属于baseClsss请勿修改，如需修改请详询管理员
]]

local RedpacketTipsLayer = class("RedpacketTipsLayer",cc.load("mvc").ViewBase)
--[[
	界面处理需要保证就算是错误数据也做到不崩溃
	在获取到数据的时候进行checkData操作
]]
RedpacketTipsLayer.Status = {
    STATUS_RED_PACKET_INIT = 0x000000, --初始化状态
    STATUS_RED_PACKET_ = 0x000001, --待领取状态
    STATUS_RED_PACKET_INIT = 0x000002,  --领取状态
}

local CURRENT_MODULE_NAME = ...
function RedpacketTipsLayer:onCreate()
	-- body
    self:addMask()
	self:initWithFilePath("RedpacketTipsLayer",CURRENT_MODULE_NAME)
    self:registerTouchEvent()
end

function RedpacketTipsLayer:registerTouchEvent()
    self.node.Btn_split:setSwallowTouches(false)
    self._touchListener = cc.EventListenerTouchOneByOne:create()
    self._touchListener:setSwallowTouches(false)
    self._touchListener:registerScriptHandler(handler(self, RedpacketTipsLayer.onTouchBegan), cc.Handler.EVENT_TOUCH_BEGAN)
    self._touchListener:registerScriptHandler(handler(self, RedpacketTipsLayer.onTouchMoved), cc.Handler.EVENT_TOUCH_MOVED)
    self._touchListener:registerScriptHandler(handler(self, RedpacketTipsLayer.onTouchEnded), cc.Handler.EVENT_TOUCH_ENDED)
    self:getEventDispatcher():addEventListenerWithSceneGraphPriority(self._touchListener, self.node.Image_background)
end

--touchbegan
function RedpacketTipsLayer:onTouchBegan(touches,event)
    return true
end

--touchmove
function RedpacketTipsLayer:onTouchMoved(touches,event)

end

--touchend
function RedpacketTipsLayer:onTouchEnded(touches,event)
    local touch_pos = touches:getLocation()
    local target = event:getCurrentTarget()
    
    local locationInNode = target:convertToNodeSpace(touch_pos);
    local s = target:getContentSize();
    local rect = cc.rect(0, 0, s.width, s.height);
     
    if cc.rectContainsPoint(rect,locationInNode) then
        --self:onSplitPacket()
        --先播拆红包动画再发送请求
        self:showSplitAni()
    else
        self:onClose()
    end
end

--播放红包弹出时候特效
function RedpacketTipsLayer:showRedAni(visible)
    if visible then
        if self.bgAni == nil then
            self.bgAni = Util.createSpineAnimationLoop(self.res_base .. "/spine/hongbaodianji_b","1",false)
            self.bgAni:setPosition(self.node.Panel_split:getContentSize().width*0.5,self.node.Panel_split:getContentSize().height*0.5)
            self.node.Panel_split:addChild(self.bgAni)
            self.bgAni:setLocalZOrder(self.node.Image_background:getLocalZOrder()-1)
        end
        if self.fontAni == nil then
            self.fontAni = Util.createSpineAnimationLoop(self.res_base .. "/spine/hongbaodianji_f","1",false)
            self.fontAni:setPosition(self.node.Panel_split:getContentSize().width*0.5,self.node.Panel_split:getContentSize().height*0.5)
            self.node.Panel_split:addChild(self.fontAni)
        end
    else
        if self.bgAni ~= nil then
            self.bgAni:clearTracks()
            self.bgAni:removeFromParent()
            self.bgAni = nil
        end
        if self.fontAni ~= nil then
            self.fontAni:clearTracks()
            self.fontAni:removeFromParent()
            self.fontAni = nil
        end
    end
end

--拆红包动画
function RedpacketTipsLayer:showSplitAni()
    self:showRedAni(false)
    --拆红包动画
    local spAni = Util.createSpineAnimation(self.res_base .. "/spine/chaihongbao","1",false,false)
    spAni:setPosition(self.node.Panel_split:getContentSize().width*0.5,self.node.Panel_split:getContentSize().height*0.5)
    self.node.Panel_split:addChild(spAni)

    spAni:registerSpineEventHandler(function(detail)
        xxtimer.delay(0.001, function() -- We need delay one frame to destory the animation, otherwise, the App will crash.
            --拆红包动画播完之后在弹出奖励
            self:onSplitPacket()
            spAni:removeFromParent();
            self:setVisible(false)
        end);
    end, sp.EventType.ANIMATION_COMPLETE);
end

function RedpacketTipsLayer:onSplitPacket()
    --点击红包上的按钮，拆开红包（发送拆包请求）
    self.part:onSplitRedPacket()
end

function RedpacketTipsLayer:updateDataInfo(data)
    --更新红包数据
    self:showRedPacketDesc(data.activityName)   --设置红包标题
    self:showRedPacketContext(data.activityDesc)    --设置红包活动内容（时间）
    self:showRedAni(true)
end

--设置红包description
function RedpacketTipsLayer:showRedPacketDesc(desc)
    self.node.Text_descript:setString(desc)
end

--设置红包context
function RedpacketTipsLayer:showRedPacketContext(context)
    self.node.Text_context:setString(context)
end

--关闭红包界面
function RedpacketTipsLayer:onClose()
    self.part:onClose()
end


return RedpacketTipsLayer