-- This file is generated by x-studio365
--[[
*名称:RedpacketTipsLayer
*描述:红包获得tips界面
*版权:Copyright © 2016-2018 深圳市三只小熊科技有限公司 版权所有
*作者:Hunter.lei
*创建日期:2017.5.2
*修改日期:2017.5.2
*备注:该类属于baseClsss请勿修改，如需修改请详询管理员
]]
-- local BasePart = require("packages.mvc.BasePart")
local CURRENT_MODULE_NAME = ...
local RedpacketTipsPart = class("RedpacketTipsPart",cc.load('mvc').PartBase) --登录模块
RedpacketTipsPart.DEFAULT_PART = {}
RedpacketTipsPart.DEFAULT_VIEW = "RedpacketTipsLayer"

require("app.model.protobufmsg" .. (PartConfig.prePath or "") .. ".RedPacketMessage_pb")
--[
-- @brief 构造函数
--]
RedpacketTipsPart.CMD = {
    SPLIT_RED_PACKET_REQ_CMD = 0x01020002,    --拆红包请求
    SPLIT_RED_PACKET_RSP_CMD = 0x01020003,    --拆红包返回响应
    --拆包协议
}
function RedpacketTipsPart:ctor(owner)
    RedpacketTipsPart.super.ctor(self, owner)
    self:initialize()
end

--[
-- @override
--]
function RedpacketTipsPart:initialize()

end

--激活模块
function RedpacketTipsPart:activate(gameId,data)
    -- gameId = 262401 --临时调试用
    if self.view ~= nil then
        self:onClose()
    end
    self.game_id = gameId
    self:registerHandleMessage()
	--激活模块
    RedpacketTipsPart.super.activate(self, CURRENT_MODULE_NAME)
    if data then
        self:setData(data)
    end
end

--刷新数据和界面
function RedpacketTipsPart:setData(data)
    if data.resultCode == 200 then  --success
        self.redpacket_data = {}
        self.redpacket_data.packetId = data.packetId    --红包id
        self.redpacket_data.gameId = data.gameId        --子游戏id
        self.redpacket_data.playerName = data.playerName    --玩家名称
        self.redpacket_data.activityId = data.activityId    --红包活动id
        self.redpacket_data.shareCode = data.shareCode    --大包id
        self.redpacket_data.activityName = data.activityName --活动名称
        self.redpacket_data.activityDesc = data.activityDesc  --活动规则
        self.redpacket_data.resultMessage = data.resultMessage    --返回内容
        self.view:updateDataInfo(self.redpacket_data)    
    end
end

--关闭界面
function RedpacketTipsPart:onClose()
    self:deactivate()
end

--反注册
function RedpacketTipsPart:deactivate()
    --local net_mode = global:getNetManager()
	--net_mode:unRegisterMsgListener(SocketConfig.MSG_GAME_OTHERLOGIN_ACK)
	--net_mode:unRegisterMsgListener(SocketConfig.MSG_GAME_SEND_SCROLL_MES)
    if self.view ~= nil then
        self.view:removeSelf()
        self.view =  nil
    end
    self.redpacket_data = {}
end

--拆红包
function RedpacketTipsPart:onSplitRedPacket()
    -- body
    local net_mode = global:getModuleWithId(ModuleDef.NET_MOD)
    local opt_msg = RedPacketMessage_pb.OpenRedPacketReqMsg()
    if self.redpacket_data then
        opt_msg.packetId = self.redpacket_data.packetId
        opt_msg.shareCode = self.redpacket_data.shareCode
        opt_msg.activityId = self.redpacket_data.activityId
        opt_msg.playerName = self.redpacket_data.playerName
        opt_msg.gameId = self.game_id
        local user = global:getGameUser()
        local props = user:getProps()
        opt_msg.wxOpenId = props.wxopenid or ""--tostring(1)
        opt_msg.userId = props.uid
        --opt_msg.opid = RoomConfig.GAME_OPERATION_PLAYER_LEFT_TABLE
        net_mode:sendProtoMsg(opt_msg,RedpacketTipsPart.CMD.SPLIT_RED_PACKET_REQ_CMD,self.game_id)
    end
end

--注册返回消息
function RedpacketTipsPart:registerHandleMessage()
    --local net_mode = global:getModuleWithId(ModuleDef.NET_MOD)
	--net_mode:registerMsgListener(RedpacketTipsPart.CMD.SPLIT_RED_PACKET_RSP_CMD,handler(self,RedpacketTipsPart.SplitRedPacketRsp))
end

--获取part id
function RedpacketTipsPart:getPartId()
	-- body
	return "RedpacketTipsPart"
end

return RedpacketTipsPart
