--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Sprite_laba
local Sprite_laba = cc.Sprite:create("app/part/teamVoice/res/laba_001.png")
Sprite_laba:setName("Sprite_laba")
Sprite_laba:setTag(2647)
Sprite_laba:setCascadeColorEnabled(true)
Sprite_laba:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_laba)
layout:setSize({width = 74.0000, height = 74.0000})
layout:setLeftMargin(-37.0000)
layout:setRightMargin(-37.0000)
layout:setTopMargin(-37.0000)
layout:setBottomMargin(-37.0000)
Sprite_laba:setBlendFunc({src = 1, dst = 771})
Node:addChild(Sprite_laba)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(45)
result['animation']:setTimeSpeed(1.0000)

--Create FileDataTimeline
local FileDataTimeline = ccs.Timeline:create()

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(false)
localFrame:setTextureName("app/part/teamVoice/res/laba_001.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(15)
localFrame:setTween(false)
localFrame:setTextureName("app/part/teamVoice/res/laba_002.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(30)
localFrame:setTween(false)
localFrame:setTextureName("app/part/teamVoice/res/laba_003.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(45)
localFrame:setTween(false)
localFrame:setTextureName("app/part/teamVoice/res/laba_001.png")
FileDataTimeline:addFrame(localFrame)

result['animation']:addTimeline(FileDataTimeline)
FileDataTimeline:setNode(Sprite_laba)
--Create Animation List

result['root'] = Node
return result;
end

return Result

