--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create speaker_btn
local speaker_btn = ccui.Button:create()
speaker_btn:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/teamVoice/res/teamvoice_picture.plist")
speaker_btn:loadTextureNormal("app/part/xymj/teamVoice/res/speaker_silent.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/teamVoice/res/teamvoice_picture.plist")
speaker_btn:loadTexturePressed("app/part/xymj/teamVoice/res/speaker_silent_click.png",1)
speaker_btn:setTitleFontSize(14)
speaker_btn:setTitleColor({r = 65, g = 65, b = 70})
speaker_btn:setScale9Enabled(true)
speaker_btn:setCapInsets({x = 15, y = 11, width = 44, height = 52})
speaker_btn:setLayoutComponentEnabled(true)
speaker_btn:setName("speaker_btn")
speaker_btn:setTag(104)
speaker_btn:setCascadeColorEnabled(true)
speaker_btn:setCascadeOpacityEnabled(true)
speaker_btn:setPosition(1148.0000, 676.0000)
if callBackProvider~=nil then
      speaker_btn:addTouchEventListener(callBackProvider("TeamVoiceLayer-UI.lua", speaker_btn, "onTouchSpeaker"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(speaker_btn)
layout:setPositionPercentX(0.8969)
layout:setPositionPercentY(0.9389)
layout:setPercentWidth(0.0578)
layout:setPercentHeight(0.1028)
layout:setSize({width = 74.0000, height = 74.0000})
layout:setHorizontalEdge(2)
layout:setVerticalEdge(2)
layout:setLeftMargin(1111.0000)
layout:setRightMargin(95.0000)
layout:setTopMargin(7.0000)
layout:setBottomMargin(639.0000)
Layer:addChild(speaker_btn)

--Create mic_btn
local mic_btn = ccui.Button:create()
mic_btn:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/teamVoice/res/teamvoice_picture.plist")
mic_btn:loadTextureNormal("app/part/xymj/teamVoice/res/forbid_aj_yy.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/teamVoice/res/teamvoice_picture.plist")
mic_btn:loadTexturePressed("app/part/xymj/teamVoice/res/forbid_aj_yy_light.png",1)
mic_btn:setTitleFontSize(14)
mic_btn:setTitleColor({r = 65, g = 65, b = 70})
mic_btn:setScale9Enabled(true)
mic_btn:setCapInsets({x = 15, y = 11, width = 44, height = 52})
mic_btn:setLayoutComponentEnabled(true)
mic_btn:setName("mic_btn")
mic_btn:setTag(105)
mic_btn:setCascadeColorEnabled(true)
mic_btn:setCascadeOpacityEnabled(true)
mic_btn:setPosition(1247.0010, 599.4477)
if callBackProvider~=nil then
      mic_btn:addTouchEventListener(callBackProvider("TeamVoiceLayer-UI.lua", mic_btn, "onTouchMic"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(mic_btn)
layout:setPositionPercentX(0.9742)
layout:setPositionPercentY(0.8326)
layout:setPercentWidth(0.0578)
layout:setPercentHeight(0.1028)
layout:setSize({width = 74.0000, height = 74.0000})
layout:setHorizontalEdge(2)
layout:setVerticalEdge(2)
layout:setLeftMargin(1210.0010)
layout:setRightMargin(-4.0006)
layout:setTopMargin(83.5523)
layout:setBottomMargin(562.4477)
Layer:addChild(mic_btn)

--Create Text_tips
local Text_tips = ccui.Text:create()
Text_tips:ignoreContentAdaptWithSize(false)
Text_tips:setFontName("font/msyh.ttf")
Text_tips:setFontSize(24)
Text_tips:setString([[不能只打开麦克风却不接受他人语音哦！]])
Text_tips:setLayoutComponentEnabled(true)
Text_tips:setName("Text_tips")
Text_tips:setTag(165)
Text_tips:setCascadeColorEnabled(true)
Text_tips:setCascadeOpacityEnabled(true)
Text_tips:setVisible(false)
Text_tips:setPosition(1075.7700, 566.0000)
Text_tips:setTextColor({r = 255, g = 255, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_tips)
layout:setPositionPercentX(0.8404)
layout:setPositionPercentY(0.7861)
layout:setPercentWidth(0.1406)
layout:setPercentHeight(0.1500)
layout:setSize({width = 180.0000, height = 108.0000})
layout:setHorizontalEdge(2)
layout:setVerticalEdge(2)
layout:setLeftMargin(985.7700)
layout:setRightMargin(114.2300)
layout:setTopMargin(100.0000)
layout:setBottomMargin(512.0000)
Layer:addChild(Text_tips)

--Create FileNode_player1
innerCSD = require("app.part.xymj.teamVoice.res.LabaNode-UI")
innerProject = innerCSD.create(callBackProvider)
local FileNode_player1 = innerProject.root
FileNode_player1.animation = innerProject.animation
FileNode_player1:setName("FileNode_player1")
FileNode_player1:setTag(2648)
FileNode_player1:setCascadeColorEnabled(true)
FileNode_player1:setCascadeOpacityEnabled(true)
FileNode_player1:setPosition(42.0000, 170.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(FileNode_player1)
layout:setPositionPercentX(0.0328)
layout:setPositionPercentY(0.2361)
layout:setHorizontalEdge(1)
layout:setVerticalEdge(1)
layout:setLeftMargin(42.0000)
layout:setRightMargin(1238.0000)
layout:setTopMargin(550.0000)
layout:setBottomMargin(170.0000)
innerProject.animation:setTimeSpeed(1.0000)
FileNode_player1:runAction(innerProject.animation)
Layer:addChild(FileNode_player1)

--Create FileNode_player2
innerCSD = require("app.part.xymj.teamVoice.res.LabaNode-UI")
innerProject = innerCSD.create(callBackProvider)
local FileNode_player2 = innerProject.root
FileNode_player2.animation = innerProject.animation
FileNode_player2:setName("FileNode_player2")
FileNode_player2:setTag(2651)
FileNode_player2:setCascadeColorEnabled(true)
FileNode_player2:setCascadeOpacityEnabled(true)
FileNode_player2:setPosition(1239.0000, 470.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(FileNode_player2)
layout:setPositionPercentX(0.9680)
layout:setPositionPercentY(0.6528)
layout:setHorizontalEdge(2)
layout:setVerticalEdge(2)
layout:setLeftMargin(1239.0000)
layout:setRightMargin(41.0000)
layout:setTopMargin(250.0000)
layout:setBottomMargin(470.0000)
innerProject.animation:setTimeSpeed(1.0000)
FileNode_player2:runAction(innerProject.animation)
Layer:addChild(FileNode_player2)

--Create FileNode_player3
innerCSD = require("app.part.xymj.teamVoice.res.LabaNode-UI")
innerProject = innerCSD.create(callBackProvider)
local FileNode_player3 = innerProject.root
FileNode_player3.animation = innerProject.animation
FileNode_player3:setName("FileNode_player3")
FileNode_player3:setTag(2654)
FileNode_player3:setCascadeColorEnabled(true)
FileNode_player3:setCascadeOpacityEnabled(true)
FileNode_player3:setPosition(931.0000, 670.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(FileNode_player3)
layout:setPositionPercentX(0.7273)
layout:setPositionPercentY(0.9306)
layout:setHorizontalEdge(2)
layout:setVerticalEdge(2)
layout:setLeftMargin(931.0000)
layout:setRightMargin(349.0000)
layout:setTopMargin(50.0000)
layout:setBottomMargin(670.0000)
innerProject.animation:setTimeSpeed(1.0000)
FileNode_player3:runAction(innerProject.animation)
Layer:addChild(FileNode_player3)

--Create FileNode_player4
innerCSD = require("app.part.xymj.teamVoice.res.LabaNode-UI")
innerProject = innerCSD.create(callBackProvider)
local FileNode_player4 = innerProject.root
FileNode_player4.animation = innerProject.animation
FileNode_player4:setName("FileNode_player4")
FileNode_player4:setTag(2657)
FileNode_player4:setCascadeColorEnabled(true)
FileNode_player4:setCascadeOpacityEnabled(true)
FileNode_player4:setPosition(41.0000, 470.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(FileNode_player4)
layout:setPositionPercentX(0.0320)
layout:setPositionPercentY(0.6528)
layout:setHorizontalEdge(1)
layout:setVerticalEdge(2)
layout:setLeftMargin(41.0000)
layout:setRightMargin(1239.0000)
layout:setTopMargin(250.0000)
layout:setBottomMargin(470.0000)
innerProject.animation:setTimeSpeed(1.0000)
FileNode_player4:runAction(innerProject.animation)
Layer:addChild(FileNode_player4)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

