--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create bg
local bg = ccui.ImageView:create()
bg:ignoreContentAdaptWithSize(false)
bg:loadTexture("app/part/xymj/gpstip/res/BackBoardS.png",0)
bg:setLayoutComponentEnabled(true)
bg:setName("bg")
bg:setTag(54)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setPosition(640.0000, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.5094)
layout:setPercentHeight(0.5778)
layout:setSize({width = 652.0000, height = 416.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(314.0000)
layout:setRightMargin(314.0000)
layout:setTopMargin(152.0000)
layout:setBottomMargin(152.0000)
Layer:addChild(bg)

--Create title_bg
local title_bg = ccui.ImageView:create()
title_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/gpstip/res/gpstips_picture.plist")
title_bg:loadTexture("app/part/xymj/gpstip/res/tipBG.png",1)
title_bg:setLayoutComponentEnabled(true)
title_bg:setName("title_bg")
title_bg:setTag(61)
title_bg:setCascadeColorEnabled(true)
title_bg:setCascadeOpacityEnabled(true)
title_bg:setPosition(326.0000, 412.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(title_bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.9904)
layout:setPercentWidth(0.3313)
layout:setPercentHeight(0.1563)
layout:setSize({width = 216.0000, height = 65.0000})
layout:setLeftMargin(218.0000)
layout:setRightMargin(218.0000)
layout:setTopMargin(-28.5000)
layout:setBottomMargin(379.5000)
bg:addChild(title_bg)

--Create tip_bg
local tip_bg = ccui.ImageView:create()
tip_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/gpstip/res/gpstips_picture.plist")
tip_bg:loadTexture("app/part/xymj/gpstip/res/gps_tip.png",1)
tip_bg:setLayoutComponentEnabled(true)
tip_bg:setName("tip_bg")
tip_bg:setTag(62)
tip_bg:setCascadeColorEnabled(true)
tip_bg:setCascadeOpacityEnabled(true)
tip_bg:setPosition(108.0000, 32.2921)
layout = ccui.LayoutComponent:bindLayoutComponent(tip_bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4968)
layout:setPercentWidth(0.7315)
layout:setPercentHeight(0.4154)
layout:setSize({width = 158.0000, height = 27.0000})
layout:setLeftMargin(29.0000)
layout:setRightMargin(29.0000)
layout:setTopMargin(19.2079)
layout:setBottomMargin(18.7921)
title_bg:addChild(tip_bg)

--Create Image_5
local Image_5 = ccui.ImageView:create()
Image_5:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/gpstip/res/gpstips_picture.plist")
Image_5:loadTexture("app/part/xymj/gpstip/res/tip.png",1)
Image_5:setLayoutComponentEnabled(true)
Image_5:setName("Image_5")
Image_5:setTag(53)
Image_5:setCascadeColorEnabled(true)
Image_5:setCascadeOpacityEnabled(true)
Image_5:setPosition(270.5419, 254.1624)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_5)
layout:setPositionPercentX(0.4149)
layout:setPositionPercentY(0.6110)
layout:setPercentWidth(0.5383)
layout:setPercentHeight(0.3269)
layout:setSize({width = 351.0000, height = 136.0000})
layout:setLeftMargin(95.0419)
layout:setRightMargin(205.9581)
layout:setTopMargin(93.8376)
layout:setBottomMargin(186.1624)
bg:addChild(Image_5)

--Create player_name1
local player_name1 = ccui.Text:create()
player_name1:ignoreContentAdaptWithSize(true)
player_name1:setTextAreaSize({width = 0, height = 0})
player_name1:setFontSize(30)
player_name1:setString([[]])
player_name1:setLayoutComponentEnabled(true)
player_name1:setName("player_name1")
player_name1:setTag(64)
player_name1:setCascadeColorEnabled(true)
player_name1:setCascadeOpacityEnabled(true)
player_name1:setAnchorPoint(0.0000, 0.5000)
player_name1:setPosition(72.0000, 120.0000)
player_name1:setTextColor({r = 128, g = 66, b = 40})
layout = ccui.LayoutComponent:bindLayoutComponent(player_name1)
layout:setPositionPercentX(0.2051)
layout:setPositionPercentY(0.8824)
layout:setLeftMargin(72.0000)
layout:setRightMargin(279.0000)
layout:setTopMargin(16.0000)
layout:setBottomMargin(120.0000)
Image_5:addChild(player_name1)

--Create player_name2
local player_name2 = ccui.Text:create()
player_name2:ignoreContentAdaptWithSize(true)
player_name2:setTextAreaSize({width = 0, height = 0})
player_name2:setFontSize(30)
player_name2:setString([[]])
player_name2:setLayoutComponentEnabled(true)
player_name2:setName("player_name2")
player_name2:setTag(80)
player_name2:setCascadeColorEnabled(true)
player_name2:setCascadeOpacityEnabled(true)
player_name2:setAnchorPoint(0.0000, 0.5000)
player_name2:setPosition(310.0000, 120.0000)
player_name2:setTextColor({r = 128, g = 66, b = 40})
layout = ccui.LayoutComponent:bindLayoutComponent(player_name2)
layout:setPositionPercentX(0.8832)
layout:setPositionPercentY(0.8824)
layout:setLeftMargin(310.0000)
layout:setRightMargin(41.0000)
layout:setTopMargin(16.0000)
layout:setBottomMargin(120.0000)
Image_5:addChild(player_name2)

--Create distance
local distance = ccui.Text:create()
distance:ignoreContentAdaptWithSize(true)
distance:setTextAreaSize({width = 0, height = 0})
distance:setFontSize(30)
distance:setString([[]])
distance:setLayoutComponentEnabled(true)
distance:setName("distance")
distance:setTag(82)
distance:setCascadeColorEnabled(true)
distance:setCascadeOpacityEnabled(true)
distance:setAnchorPoint(0.0000, 0.5000)
distance:setPosition(255.9407, 69.9735)
distance:setTextColor({r = 255, g = 0, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(distance)
layout:setPositionPercentX(0.7292)
layout:setPositionPercentY(0.5145)
layout:setLeftMargin(255.9407)
layout:setRightMargin(95.0593)
layout:setTopMargin(66.0265)
layout:setBottomMargin(69.9735)
Image_5:addChild(distance)

--Create close_vip_btn
local close_vip_btn = ccui.Button:create()
close_vip_btn:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/gpstip/res/gpstips_picture.plist")
close_vip_btn:loadTextureNormal("app/part/xymj/gpstip/res/diss_btn-l.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/gpstip/res/gpstips_picture.plist")
close_vip_btn:loadTexturePressed("app/part/xymj/gpstip/res/diss_btn.png",1)
close_vip_btn:loadTextureDisabled("Default/Button_Disable.png",0)
close_vip_btn:setTitleFontSize(14)
close_vip_btn:setTitleColor({r = 65, g = 65, b = 70})
close_vip_btn:setScale9Enabled(true)
close_vip_btn:setCapInsets({x = 15, y = 11, width = 154, height = 53})
close_vip_btn:setLayoutComponentEnabled(true)
close_vip_btn:setName("close_vip_btn")
close_vip_btn:setTag(56)
close_vip_btn:setCascadeColorEnabled(true)
close_vip_btn:setCascadeOpacityEnabled(true)
close_vip_btn:setPosition(196.9994, 73.9999)
if callBackProvider~=nil then
      close_vip_btn:addClickEventListener(callBackProvider("GpsTipLayer-UI.lua", close_vip_btn, "CloseVipRoomClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(close_vip_btn)
layout:setPositionPercentX(0.3021)
layout:setPositionPercentY(0.1779)
layout:setPercentWidth(0.2822)
layout:setPercentHeight(0.1803)
layout:setSize({width = 184.0000, height = 75.0000})
layout:setLeftMargin(104.9994)
layout:setRightMargin(363.0006)
layout:setTopMargin(304.5001)
layout:setBottomMargin(36.4999)
bg:addChild(close_vip_btn)

--Create cancel_btn
local cancel_btn = ccui.Button:create()
cancel_btn:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/gpstip/res/gpstips_picture.plist")
cancel_btn:loadTextureNormal("app/part/xymj/gpstip/res/tc_qxl.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/gpstip/res/gpstips_picture.plist")
cancel_btn:loadTexturePressed("app/part/xymj/gpstip/res/tc_qx.png",1)
cancel_btn:loadTextureDisabled("Default/Button_Disable.png",0)
cancel_btn:setTitleFontSize(14)
cancel_btn:setTitleColor({r = 65, g = 65, b = 70})
cancel_btn:setScale9Enabled(true)
cancel_btn:setCapInsets({x = 15, y = 11, width = 153, height = 52})
cancel_btn:setLayoutComponentEnabled(true)
cancel_btn:setName("cancel_btn")
cancel_btn:setTag(57)
cancel_btn:setCascadeColorEnabled(true)
cancel_btn:setCascadeOpacityEnabled(true)
cancel_btn:setPosition(451.9971, 73.0000)
if callBackProvider~=nil then
      cancel_btn:addClickEventListener(callBackProvider("GpsTipLayer-UI.lua", cancel_btn, "CancelClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(cancel_btn)
layout:setPositionPercentX(0.6932)
layout:setPositionPercentY(0.1755)
layout:setPercentWidth(0.2807)
layout:setPercentHeight(0.1779)
layout:setSize({width = 183.0000, height = 74.0000})
layout:setLeftMargin(360.4971)
layout:setRightMargin(108.5029)
layout:setTopMargin(306.0000)
layout:setBottomMargin(36.0000)
bg:addChild(cancel_btn)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

