-- This file is generated by x-studio365
--[[
*名称:RewardTipsLayer
*描述:奖励获得tips界面
*版权:Copyright © 2016-2018 深圳市三只小熊科技有限公司 版权所有
*作者:Hunter.lei
*创建日期:2017.5.2
*修改日期:2017.5.2
*备注:该类属于baseClsss请勿修改，如需修改请详询管理员
]]
local CURRENT_MODULE_NAME = ...
local RewardTipsPart = class("RewardTipsPart",cc.load('mvc').PartBase) --登录模块
RewardTipsPart.DEFAULT_PART = {}
RewardTipsPart.DEFAULT_VIEW = "RewardTipsLayer"
--[
-- @brief 构造函数
--]
RewardTipsPart.CMD = {
    --MSG_GAME_OPERATION = 0xc30008, --领取红包协议命令
}
function RewardTipsPart:ctor(owner)
    RewardTipsPart.super.ctor(self, owner)
    self:initialize()
    
end

--[
-- @override
--]
function RewardTipsPart:initialize()

end

--激活模块
function RewardTipsPart:activate(gameId,data)
    if self.view ~= nil then
        self:onClose()
    end
    self.game_id = gameId
	--激活模块
    RewardTipsPart.super.activate(self, CURRENT_MODULE_NAME)
    self:setDataInfo(data)
end

--刷新数据和界面
function RewardTipsPart:setDataInfo(data) 
    if data.resultCode == 200 then  --success
        self.redpacket_data = {}
        self.redpacket_data.prize = data.prize    --奖励数量
        self.redpacket_data.prizeType = data.prizeType        --奖励类型
        self.redpacket_data.isNeedShare = data.isNeedShare    --是否需要分享
        self.redpacket_data.shareLink = data.shareLink    --朋友圈分享链接
        self.redpacket_data.resultMessage = data.resultMessage    --返回内容
        self.view:setDataInfo(data) 
    end
end

--分享到朋友圈
function RewardTipsPart:shareToWX() 
    local shareUrl = self.redpacket_data.shareLink
    local shareContent = ""
    local shareTitle = "天降红包雨，现金送不停！快来抢我分享的红包吧！"
    self.view:shareToWXCircleFriend(shareTitle,shareContent,shareUrl)
    --global:setShareState(true)
end

--打开红包管理界面
function RewardTipsPart:openRedpacketLayer()
   self.owner:ClickRedPacketEvent()
end

--关闭界面
function RewardTipsPart:onClose()
    -- body
    --local net_mode = global:getModuleWithId(ModuleDef.NET_MOD)
    --local opt_msg = ycmj_message_pb.PlayerGameOpertaion()
    --opt_msg.opid = RoomConfig.GAME_OPERATION_PLAYER_LEFT_TABLE
    --net_mode:sendProtoMsg(opt_msg,VipOverPart.CMD.MSG_GAME_OPERATION,self.game_id)
    self:deactivate()
end

function RewardTipsPart:deactivate()
    self.view:removeSelf()
    self.view =  nil
end

function RewardTipsPart:getPartId()
	-- body
	return "RewardTipsPart"
end

return RewardTipsPart