--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create root
local root = ccui.Layout:create()
root:ignoreContentAdaptWithSize(false)
root:setClippingEnabled(false)
root:setBackGroundColorOpacity(102)
root:setTouchEnabled(true);
root:setLayoutComponentEnabled(true)
root:setName("root")
root:setTag(68)
root:setCascadeColorEnabled(true)
root:setCascadeOpacityEnabled(true)
root:setAnchorPoint(0.5000, 0.5000)
root:setPosition(640.0000, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(root)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
Layer:addChild(root)

--Create effect_root
local effect_root = ccui.Layout:create()
effect_root:ignoreContentAdaptWithSize(false)
effect_root:setClippingEnabled(false)
effect_root:setBackGroundColorOpacity(102)
effect_root:setTouchEnabled(true);
effect_root:setLayoutComponentEnabled(true)
effect_root:setName("effect_root")
effect_root:setTag(108)
effect_root:setCascadeColorEnabled(true)
effect_root:setCascadeOpacityEnabled(true)
effect_root:setAnchorPoint(0.5000, 0.5000)
effect_root:setPosition(640.0000, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(effect_root)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
root:addChild(effect_root)

--Create tips_bg
local tips_bg = ccui.ImageView:create()
tips_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjmatch/winMatch/res/winMatch_picture.plist")
tips_bg:loadTexture("app/part/xymj/mjmatch/winMatch/res/award_bg.png",1)
tips_bg:setLayoutComponentEnabled(true)
tips_bg:setName("tips_bg")
tips_bg:setTag(105)
tips_bg:setCascadeColorEnabled(true)
tips_bg:setCascadeOpacityEnabled(true)
tips_bg:setPosition(640.0000, 309.3840)
layout = ccui.LayoutComponent:bindLayoutComponent(tips_bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4297)
layout:setPercentWidth(0.3555)
layout:setPercentHeight(0.4056)
layout:setSize({width = 455.0000, height = 292.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(412.5000)
layout:setRightMargin(412.5000)
layout:setTopMargin(264.6160)
layout:setBottomMargin(163.3840)
root:addChild(tips_bg)

--Create tips
local tips = ccui.ImageView:create()
tips:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjmatch/loseMatch/res/loseMatch_picture.plist")
tips:loadTexture("app/part/xymj/mjmatch/loseMatch/res/lose_tips.png",1)
tips:setLayoutComponentEnabled(true)
tips:setName("tips")
tips:setTag(106)
tips:setCascadeColorEnabled(true)
tips:setCascadeOpacityEnabled(true)
tips:setPosition(229.5066, 74.7250)
layout = ccui.LayoutComponent:bindLayoutComponent(tips)
layout:setPositionPercentX(0.5044)
layout:setPositionPercentY(0.2559)
layout:setPercentWidth(0.9297)
layout:setPercentHeight(0.2740)
layout:setSize({width = 423.0000, height = 80.0000})
layout:setLeftMargin(18.0066)
layout:setRightMargin(13.9934)
layout:setTopMargin(177.2750)
layout:setBottomMargin(34.7250)
tips_bg:addChild(tips)

--Create number
local number = ccui.TextAtlas:create([[66]],
													"app/part/xymj/mjmatch/loseMatch/res/number.png",
													38,
													59,
													"0")
number:setLayoutComponentEnabled(true)
number:setName("number")
number:setTag(107)
number:setCascadeColorEnabled(true)
number:setCascadeOpacityEnabled(true)
number:setPosition(367.9997, 105.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(number)
layout:setPositionPercentX(0.8088)
layout:setPositionPercentY(0.3596)
layout:setPercentWidth(0.1670)
layout:setPercentHeight(0.2021)
layout:setSize({width = 76.0000, height = 59.0000})
layout:setLeftMargin(329.9997)
layout:setRightMargin(49.0003)
layout:setTopMargin(157.5000)
layout:setBottomMargin(75.5000)
tips_bg:addChild(number)

--Create share
local share = ccui.Button:create()
share:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjmatch/readyMatch/res/readyMatch_picture.plist")
share:loadTextureNormal("app/part/xymj/mjmatch/readyMatch/res/btn_normal_yellow.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjmatch/readyMatch/res/readyMatch_picture.plist")
share:loadTexturePressed("app/part/xymj/mjmatch/readyMatch/res/btn_click_yellow.png",1)
share:loadTextureDisabled("Default/Button_Disable.png",0)
share:setTitleFontSize(14)
share:setTitleColor({r = 65, g = 65, b = 70})
share:setScale9Enabled(true)
share:setCapInsets({x = 15, y = 11, width = 176, height = 57})
share:setLayoutComponentEnabled(true)
share:setName("share")
share:setTag(109)
share:setCascadeColorEnabled(true)
share:setCascadeOpacityEnabled(true)
share:setPosition(507.6480, 113.1763)
if callBackProvider~=nil then
      share:addClickEventListener(callBackProvider("loseMatchLayer-UI.lua", share, "onShareClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(share)
layout:setPositionPercentX(0.3966)
layout:setPositionPercentY(0.1572)
layout:setPercentWidth(0.1609)
layout:setPercentHeight(0.1097)
layout:setSize({width = 206.0000, height = 79.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(1)
layout:setLeftMargin(404.6480)
layout:setRightMargin(669.3520)
layout:setTopMargin(567.3237)
layout:setBottomMargin(73.6763)
Layer:addChild(share)

--Create Image_3
local Image_3 = ccui.ImageView:create()
Image_3:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjmatch/loseMatch/res/loseMatch_picture.plist")
Image_3:loadTexture("app/part/xymj/mjmatch/loseMatch/res/font_qaw.png",1)
Image_3:setLayoutComponentEnabled(true)
Image_3:setName("Image_3")
Image_3:setTag(110)
Image_3:setCascadeColorEnabled(true)
Image_3:setCascadeOpacityEnabled(true)
Image_3:setPosition(102.6704, 41.8293)
if callBackProvider~=nil then
      Image_3:addClickEventListener(callBackProvider("loseMatchLayer-UI.lua", Image_3, "onSureClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(Image_3)
layout:setPositionPercentX(0.4984)
layout:setPositionPercentY(0.5295)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 206.0000, height = 79.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(1)
layout:setLeftMargin(-0.3296)
layout:setRightMargin(0.3296)
layout:setTopMargin(-2.3293)
layout:setBottomMargin(2.3293)
share:addChild(Image_3)

--Create sure
local sure = ccui.Button:create()
sure:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjmatch/readyMatch/res/readyMatch_picture.plist")
sure:loadTextureNormal("app/part/xymj/mjmatch/readyMatch/res/btn_normal_yellow.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjmatch/readyMatch/res/readyMatch_picture.plist")
sure:loadTexturePressed("app/part/xymj/mjmatch/readyMatch/res/btn_click_yellow.png",1)
sure:loadTextureDisabled("Default/Button_Disable.png",0)
sure:setTitleFontSize(14)
sure:setTitleColor({r = 65, g = 65, b = 70})
sure:setScale9Enabled(true)
sure:setCapInsets({x = 15, y = 11, width = 176, height = 57})
sure:setLayoutComponentEnabled(true)
sure:setName("sure")
sure:setTag(111)
sure:setCascadeColorEnabled(true)
sure:setCascadeOpacityEnabled(true)
sure:setPosition(790.2720, 112.4056)
if callBackProvider~=nil then
      sure:addClickEventListener(callBackProvider("loseMatchLayer-UI.lua", sure, "onSureClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(sure)
layout:setPositionPercentX(0.6174)
layout:setPositionPercentY(0.1561)
layout:setPercentWidth(0.1609)
layout:setPercentHeight(0.1097)
layout:setSize({width = 206.0000, height = 79.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(1)
layout:setLeftMargin(687.2720)
layout:setRightMargin(386.7280)
layout:setTopMargin(568.0944)
layout:setBottomMargin(72.9056)
Layer:addChild(sure)

--Create Image_2
local Image_2 = ccui.ImageView:create()
Image_2:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("app/part/xymj/mjmatch/winMatch/res/winMatch_picture.plist")
Image_2:loadTexture("app/part/xymj/mjmatch/winMatch/res/font_sure.png",1)
Image_2:setLayoutComponentEnabled(true)
Image_2:setName("Image_2")
Image_2:setTag(112)
Image_2:setCascadeColorEnabled(true)
Image_2:setCascadeOpacityEnabled(true)
Image_2:setPosition(101.1048, 39.6124)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_2)
layout:setPositionPercentX(0.4908)
layout:setPositionPercentY(0.5014)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 206.0000, height = 79.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(1)
layout:setLeftMargin(-1.8952)
layout:setRightMargin(1.8952)
layout:setTopMargin(-0.1124)
layout:setBottomMargin(0.1124)
sure:addChild(Image_2)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

